In [5]:
import time
start_time = time.time()

dataset = []

with open("mushroom") as fp:  
    line = fp.readline().split(" ")[:-1]
    cnt = 1
    while line:
        line = list(map(int, line))
        line.sort()
        dataset.append(line)
        line = fp.readline().split(" ")[:-1]
        #print("\n")
        
        cnt += 1



23


In [78]:
global number
number = 0
min_sup = int(cnt * .3)

In [79]:
def isFreq(temp):
    #print("tempu",temp)
    temp =np.asarray(temp)
    pp = 0
    for i in range(len(data)):
        cc = 0
        for j in range(len(temp)):
            #print("aslkh",temp[j],data[i])
            if temp[j] in data[i]:
                cc+=1
            else:
                break
            
        if cc==len(temp):
            #print("Matched: ",data[i])
            pp+=1
        
    return pp

In [80]:
def join(l1):
    res = []
    for i in range(len(l1)):
        for k in range(len(l1)):
            if i>=k:
                continue
            if set(l1[i][0:(len(l1[i])-1)]) == set(l1[k][0:len(l1[k])-1]):
                new = l1[i]
                new = np.append(new,l1[k][len(l1[k])-1])
                #print()
                res.append(new)
        
    return res
    

In [81]:

from itertools import chain
import numpy as np

i=0
j=0
#data = [['1','2','5'],['2','4'],['2','3'],['1','2','4'],['1','3'],['2','3'],['1','3'],['1','2','3','5'],['1','2','3']]
#data = [[1,2,5],[2,4],[2,3],[1,2,4],[1,3],[2,3],[1,3],[1,2,3,5],[1,2,3]]
data = dataset
data = np.asarray(data)

print("data",data)



flat = list(chain.from_iterable(data))
ar = np.reshape(np.asarray(np.unique(flat)),(-1,1))


data [[  1   3   9 ...  98 107 113]
 [  2   3   9 ...  99 108 114]
 [  2   4   9 ...  99 108 115]
 ...
 [  2   6   9 ... 106 112 119]
 [  1   7  10 ... 102 110 119]
 [  2   3   9 ... 104 112 119]]


In [82]:
import itertools
def genItem(tempres,tempcnt):
    temp = np.asarray(join(tempres))
    #ALL ITEM GENERATED
    global number
    res = []
    cnt = []
    
    exist = 0

    for i in range(len(temp)):
        pruneitem = np.array(list(itertools.combinations(temp[i],len(temp[i])-1)))
        #pruneitem = pruneitem[len(pruneitem)-1]
        exist = 0
        for y in range(len(pruneitem)):
            for x in range(len(temp)):
                c = 0
                for j in range(len(pruneitem[y])):
                    if pruneitem[y][j] in temp[x]:
                        c+=1
                    else:
                        break

                if c==len(pruneitem[y]):
                    exist+=1
                    break
            if exist < len(pruneitem):
                continue
        
        freq = isFreq(temp[i])
        #print(freq)
        if freq<min_sup:
            continue
        
        number+=1
        print(number,":",temp[i],freq)
        res.append(temp[i])
        cnt.append(freq)
        
    return np.asarray(res),cnt


In [83]:
print(len(ar))

119


In [84]:
number=0
arcnt = []

ln = len(ar)
index = []

#1-ITEM GENERATION

for i in range(ln):
    c=0
    for j in range(len(data)):
        if ar[i] in data[j]:
            c+=1
    
    if c<min_sup:
        #print("delete",i)
        index.append(i)
        ln-=1
        continue
        
    arcnt.append(c)

ar = np.delete(ar,index,0)    
for i in range(len(ar)):
    number+=1
    print(number,":",ar[i],arcnt[i])
    

#2-ITEM GENERATION
cnt1 = []
res1 = []

global number
#print("ar",ar)
for i in range(len(ar)):
        for k in range(len(ar)):
            if i>=k:
                continue
            
            if (ar[i] in ar) and (ar[k] in ar): 
                new = np.asarray([])
                new = np.append(new,ar[i])
                new = np.append(new,ar[k])

                itemFreq = isFreq(new)

                if itemFreq<min_sup:
                    continue
                number+=1
                print(number,":",new,itemFreq)
                res1.append(new)
                cnt1.append(itemFreq)
                

# >2-ITEM GENERATION
res1 = np.asarray(res1)

fixres = res1
fixcount = cnt1

locres = res1
loccnt = cnt1
while True:
    locres,loccnt = genItem(locres,loccnt)
    if len(locres)==0:
        print("FINISHED")
        break
print("--- %s seconds ---" % (time.time() - start_time))


1 : [1] 3916
2 : [2] 4208
3 : [3] 3656
4 : [6] 3152
5 : [9] 2556
6 : [10] 3244
7 : [23] 3376
8 : [24] 4748
9 : [28] 3528
10 : [34] 7914
11 : [36] 6812
12 : [38] 2512
13 : [39] 5612
14 : [52] 3516
15 : [53] 4608
16 : [56] 3776
17 : [58] 2480
18 : [59] 5176
19 : [63] 4936
20 : [67] 4464
21 : [76] 4384
22 : [85] 8124
23 : [86] 7924
24 : [90] 7488
25 : [93] 3968
26 : [94] 2776
27 : [110] 4040
28 : [116] 3148
29 : [ 1. 24.] 3292
30 : [ 1. 34.] 3898
31 : [ 1. 36.] 3804
32 : [ 1. 85.] 3916
33 : [ 1. 86.] 3908
34 : [ 1. 90.] 3808
35 : [  1. 110.] 2848
36 : [ 2. 23.] 2752
37 : [ 2. 28.] 3408
38 : [ 2. 34.] 4016
39 : [ 2. 36.] 3008
40 : [ 2. 39.] 3920
41 : [ 2. 53.] 2592
42 : [ 2. 59.] 3640
43 : [ 2. 63.] 3400
44 : [ 2. 67.] 2752
45 : [ 2. 76.] 2704
46 : [ 2. 85.] 4208
47 : [ 2. 86.] 4016
48 : [ 2. 90.] 3680
49 : [ 2. 93.] 3152
50 : [ 3. 34.] 3602
51 : [ 3. 36.] 3016
52 : [ 3. 39.] 2632
53 : [ 3. 85.] 3656
54 : [ 3. 86.] 3608
55 : [ 3. 90.] 3464
56 : [ 6. 34.] 3098
57 : [ 6. 36.] 2700
58 : [ 6. 

368 : [ 24.  85. 110.] 2720
369 : [24. 86. 90.] 4208
370 : [24. 86. 94.] 2576
371 : [ 24.  86. 110.] 2624
372 : [24. 90. 94.] 2584
373 : [ 24.  90. 110.] 2720
374 : [28. 34. 39.] 3096
375 : [28. 34. 53.] 2496
376 : [28. 34. 59.] 2728
377 : [28. 34. 63.] 2680
378 : [28. 34. 85.] 3336
379 : [28. 34. 86.] 3328
380 : [28. 34. 90.] 2736
381 : [28. 39. 53.] 2496
382 : [28. 39. 59.] 2744
383 : [28. 39. 63.] 2744
384 : [28. 39. 85.] 3288
385 : [28. 39. 86.] 3096
386 : [28. 39. 90.] 2688
387 : [28. 53. 85.] 2496
388 : [28. 53. 86.] 2496
389 : [28. 53. 90.] 2496
390 : [28. 59. 63.] 2596
391 : [28. 59. 85.] 2920
392 : [28. 59. 86.] 2728
393 : [28. 59. 90.] 2480
394 : [28. 63. 85.] 2872
395 : [28. 63. 86.] 2680
396 : [28. 85. 86.] 3328
397 : [28. 85. 90.] 2928
398 : [28. 86. 90.] 2728
399 : [34. 36. 39.] 4346
400 : [34. 36. 52.] 2858
401 : [34. 36. 53.] 3744
402 : [34. 36. 56.] 3528
403 : [34. 36. 59.] 4232
404 : [34. 36. 63.] 3992
405 : [34. 36. 67.] 3160
406 : [34. 36. 76.] 3128
407 : [34. 36. 8

684 : [ 2. 23. 34. 59.] 2752
685 : [ 2. 23. 34. 63.] 2560
686 : [ 2. 23. 34. 85.] 2752
687 : [ 2. 23. 34. 86.] 2752
688 : [ 2. 23. 34. 90.] 2528
689 : [ 2. 23. 34. 93.] 2560
690 : [ 2. 23. 36. 39.] 2656
691 : [ 2. 23. 36. 59.] 2656
692 : [ 2. 23. 36. 63.] 2464
693 : [ 2. 23. 36. 85.] 2656
694 : [ 2. 23. 36. 86.] 2656
695 : [ 2. 23. 36. 93.] 2464
696 : [ 2. 23. 39. 59.] 2656
697 : [ 2. 23. 39. 63.] 2464
698 : [ 2. 23. 39. 85.] 2656
699 : [ 2. 23. 39. 86.] 2656
700 : [ 2. 23. 39. 93.] 2464
701 : [ 2. 23. 59. 63.] 2560
702 : [ 2. 23. 59. 85.] 2752
703 : [ 2. 23. 59. 86.] 2752
704 : [ 2. 23. 59. 90.] 2528
705 : [ 2. 23. 59. 93.] 2560
706 : [ 2. 23. 63. 85.] 2560
707 : [ 2. 23. 63. 86.] 2560
708 : [ 2. 23. 85. 86.] 2752
709 : [ 2. 23. 85. 90.] 2528
710 : [ 2. 23. 85. 93.] 2560
711 : [ 2. 23. 86. 90.] 2528
712 : [ 2. 23. 86. 93.] 2560
713 : [ 2. 23. 90. 93.] 2528
714 : [ 2. 28. 34. 39.] 3024
715 : [ 2. 28. 34. 53.] 2496
716 : [ 2. 28. 34. 59.] 2648
717 : [ 2. 28. 34. 63.] 2600
718 : [ 2. 28.

967 : [24. 34. 53. 86.] 2496
968 : [24. 34. 53. 90.] 2496
969 : [24. 34. 53. 94.] 2496
970 : [24. 34. 85. 86.] 4530
971 : [24. 34. 85. 90.] 4216
972 : [24. 34. 85. 94.] 2584
973 : [ 24.  34.  85. 110.] 2624
974 : [24. 34. 86. 90.] 4208
975 : [24. 34. 86. 94.] 2576
976 : [ 24.  34.  86. 110.] 2624
977 : [24. 34. 90. 94.] 2584
978 : [ 24.  34.  90. 110.] 2624
979 : [24. 36. 85. 86.] 3348
980 : [24. 36. 85. 90.] 3488
981 : [ 24.  36.  85. 110.] 2624
982 : [24. 36. 86. 90.] 3296
983 : [ 24.  36.  86. 110.] 2528
984 : [ 24.  36.  90. 110.] 2624
985 : [24. 53. 85. 86.] 2496
986 : [24. 53. 85. 90.] 2496
987 : [24. 53. 85. 94.] 2496
988 : [24. 53. 86. 90.] 2496
989 : [24. 53. 86. 94.] 2496
990 : [24. 53. 90. 94.] 2496
991 : [24. 85. 86. 90.] 4208
992 : [24. 85. 86. 94.] 2576
993 : [ 24.  85.  86. 110.] 2624
994 : [24. 85. 90. 94.] 2584
995 : [ 24.  85.  90. 110.] 2720
996 : [24. 86. 90. 94.] 2576
997 : [ 24.  86.  90. 110.] 2624
998 : [28. 34. 39. 53.] 2496
999 : [28. 34. 39. 59.] 2552
1000 : 

1238 : [36. 59. 63. 90.] 3384
1239 : [36. 59. 63. 93.] 3056
1240 : [36. 59. 67. 85.] 2552
1241 : [36. 59. 67. 86.] 2552
1242 : [36. 59. 76. 85.] 2552
1243 : [36. 59. 76. 86.] 2552
1244 : [36. 59. 85. 86.] 4232
1245 : [36. 59. 85. 90.] 4128
1246 : [36. 59. 85. 93.] 3320
1247 : [36. 59. 86. 90.] 3936
1248 : [36. 59. 86. 93.] 3128
1249 : [36. 59. 90. 93.] 3216
1250 : [36. 63. 85. 86.] 3992
1251 : [36. 63. 85. 90.] 3888
1252 : [36. 63. 85. 93.] 3128
1253 : [36. 63. 86. 90.] 3696
1254 : [36. 63. 86. 93.] 2936
1255 : [36. 63. 90. 93.] 3024
1256 : [36. 67. 85. 86.] 3160
1257 : [36. 67. 85. 90.] 2960
1258 : [36. 67. 86. 90.] 2960
1259 : [36. 76. 85. 86.] 3128
1260 : [36. 76. 85. 90.] 2928
1261 : [36. 76. 86. 90.] 2928
1262 : [36. 85. 86. 90.] 6272
1263 : [36. 85. 86. 93.] 3288
1264 : [ 36.  85.  86. 110.] 3752
1265 : [ 36.  85.  86. 116.] 2956
1266 : [36. 85. 90. 93.] 3360
1267 : [ 36.  85.  90. 110.] 3760
1268 : [ 36.  85.  90. 116.] 2912
1269 : [36. 86. 90. 93.] 3168
1270 : [ 36.  86.  90. 1

1491 : [ 2. 28. 39. 85. 90.] 2688
1492 : [ 2. 28. 39. 86. 90.] 2496
1493 : [ 2. 28. 53. 85. 86.] 2496
1494 : [ 2. 28. 53. 85. 90.] 2496
1495 : [ 2. 28. 53. 86. 90.] 2496
1496 : [ 2. 28. 59. 63. 85.] 2516
1497 : [ 2. 28. 59. 85. 86.] 2648
1498 : [ 2. 28. 59. 85. 90.] 2472
1499 : [ 2. 28. 63. 85. 86.] 2600
1500 : [ 2. 28. 85. 86. 90.] 2688
1501 : [ 2. 34. 36. 39. 59.] 2656
1502 : [ 2. 34. 36. 39. 63.] 2464
1503 : [ 2. 34. 36. 39. 85.] 2672
1504 : [ 2. 34. 36. 39. 86.] 2672
1505 : [ 2. 34. 36. 39. 93.] 2480
1506 : [ 2. 34. 36. 59. 63.] 2560
1507 : [ 2. 34. 36. 59. 85.] 2800
1508 : [ 2. 34. 36. 59. 86.] 2800
1509 : [ 2. 34. 36. 59. 90.] 2576
1510 : [ 2. 34. 36. 59. 93.] 2560
1511 : [ 2. 34. 36. 63. 85.] 2560
1512 : [ 2. 34. 36. 63. 86.] 2560
1513 : [ 2. 34. 36. 85. 86.] 2816
1514 : [ 2. 34. 36. 85. 90.] 2576
1515 : [ 2. 34. 36. 85. 93.] 2576
1516 : [ 2. 34. 36. 86. 90.] 2576
1517 : [ 2. 34. 36. 86. 93.] 2576
1518 : [ 2. 34. 36. 90. 93.] 2528
1519 : [ 2. 34. 39. 53. 85.] 2496
1520 : [ 2. 34

1732 : [23. 36. 85. 86. 90.] 2976
1733 : [23. 36. 85. 86. 93.] 3080
1734 : [23. 36. 85. 90. 93.] 2976
1735 : [23. 36. 86. 90. 93.] 2976
1736 : [23. 39. 59. 63. 85.] 2608
1737 : [23. 39. 59. 63. 86.] 2608
1738 : [23. 39. 59. 85. 86.] 2872
1739 : [23. 39. 59. 85. 90.] 2576
1740 : [23. 39. 59. 85. 93.] 2680
1741 : [23. 39. 59. 86. 90.] 2576
1742 : [23. 39. 59. 86. 93.] 2680
1743 : [23. 39. 59. 90. 93.] 2576
1744 : [23. 39. 63. 85. 86.] 2680
1745 : [23. 39. 63. 85. 93.] 2488
1746 : [23. 39. 63. 86. 93.] 2488
1747 : [23. 39. 85. 86. 90.] 2720
1748 : [23. 39. 85. 86. 93.] 2824
1749 : [23. 39. 85. 90. 93.] 2720
1750 : [23. 39. 86. 90. 93.] 2720
1751 : [23. 59. 63. 85. 86.] 2968
1752 : [23. 59. 63. 85. 90.] 2672
1753 : [23. 59. 63. 85. 93.] 2776
1754 : [23. 59. 63. 86. 90.] 2672
1755 : [23. 59. 63. 86. 93.] 2776
1756 : [23. 59. 63. 90. 93.] 2672
1757 : [23. 59. 85. 86. 90.] 2936
1758 : [23. 59. 85. 86. 93.] 3040
1759 : [23. 59. 85. 90. 93.] 2936
1760 : [23. 59. 86. 90. 93.] 2936
1761 : [23. 63

1970 : [34. 63. 67. 86. 90.] 2720
1971 : [34. 63. 76. 85. 86.] 3040
1972 : [34. 63. 76. 85. 90.] 2696
1973 : [34. 63. 76. 86. 90.] 2696
1974 : [34. 63. 85. 86. 90.] 4304
1975 : [34. 63. 85. 86. 93.] 3280
1976 : [34. 63. 85. 90. 93.] 3032
1977 : [34. 63. 86. 90. 93.] 3032
1978 : [34. 67. 76. 85. 86.] 3520
1979 : [34. 67. 76. 85. 90.] 3080
1980 : [34. 67. 76. 86. 90.] 3080
1981 : [34. 67. 85. 86. 90.] 3976
1982 : [34. 67. 85. 86. 93.] 2608
1983 : [34. 76. 85. 86. 90.] 3896
1984 : [34. 76. 85. 86. 93.] 2608
1985 : [34. 85. 86. 90. 93.] 3368
1986 : [34. 85. 86. 90. 94.] 2576
1987 : [ 34.  85.  86.  90. 110.] 3856
1988 : [ 34.  85.  86.  90. 116.] 3104
1989 : [36. 39. 56. 85. 86.] 3432
1990 : [36. 39. 56. 85. 90.] 3312
1991 : [36. 39. 56. 86. 90.] 3312
1992 : [36. 39. 59. 63. 85.] 2800
1993 : [36. 39. 59. 63. 86.] 2608
1994 : [36. 39. 59. 63. 90.] 2504
1995 : [36. 39. 59. 63. 93.] 2608
1996 : [36. 39. 59. 85. 86.] 2872
1997 : [36. 39. 59. 85. 90.] 2768
1998 : [36. 39. 59. 85. 93.] 2872
1999

2195 : [ 2. 34. 36. 39. 59. 86.] 2656
2196 : [ 2. 34. 36. 39. 59. 93.] 2464
2197 : [ 2. 34. 36. 39. 63. 85.] 2464
2198 : [ 2. 34. 36. 39. 63. 86.] 2464
2199 : [ 2. 34. 36. 39. 85. 86.] 2672
2200 : [ 2. 34. 36. 39. 85. 93.] 2480
2201 : [ 2. 34. 36. 39. 86. 93.] 2480
2202 : [ 2. 34. 36. 59. 63. 85.] 2560
2203 : [ 2. 34. 36. 59. 63. 86.] 2560
2204 : [ 2. 34. 36. 59. 85. 86.] 2800
2205 : [ 2. 34. 36. 59. 85. 90.] 2576
2206 : [ 2. 34. 36. 59. 85. 93.] 2560
2207 : [ 2. 34. 36. 59. 86. 90.] 2576
2208 : [ 2. 34. 36. 59. 86. 93.] 2560
2209 : [ 2. 34. 36. 59. 90. 93.] 2528
2210 : [ 2. 34. 36. 63. 85. 86.] 2560
2211 : [ 2. 34. 36. 85. 86. 90.] 2576
2212 : [ 2. 34. 36. 85. 86. 93.] 2576
2213 : [ 2. 34. 36. 85. 90. 93.] 2528
2214 : [ 2. 34. 36. 86. 90. 93.] 2528
2215 : [ 2. 34. 39. 53. 85. 86.] 2496
2216 : [ 2. 34. 39. 53. 85. 90.] 2496
2217 : [ 2. 34. 39. 53. 86. 90.] 2496
2218 : [ 2. 34. 39. 59. 63. 85.] 2728
2219 : [ 2. 34. 39. 59. 63. 86.] 2728
2220 : [ 2. 34. 39. 59. 85. 86.] 3184
2221 : [ 2. 

2410 : [34. 36. 39. 56. 85. 90.] 3312
2411 : [34. 36. 39. 56. 86. 90.] 3312
2412 : [34. 36. 39. 59. 63. 85.] 2608
2413 : [34. 36. 39. 59. 63. 86.] 2608
2414 : [34. 36. 39. 59. 85. 86.] 2872
2415 : [34. 36. 39. 59. 85. 90.] 2576
2416 : [34. 36. 39. 59. 85. 93.] 2680
2417 : [34. 36. 39. 59. 86. 90.] 2576
2418 : [34. 36. 39. 59. 86. 93.] 2680
2419 : [34. 36. 39. 59. 90. 93.] 2576
2420 : [34. 36. 39. 63. 85. 86.] 2680
2421 : [34. 36. 39. 63. 85. 93.] 2488
2422 : [34. 36. 39. 63. 86. 93.] 2488
2423 : [34. 36. 39. 85. 86. 90.] 4016
2424 : [34. 36. 39. 85. 86. 93.] 2840
2425 : [34. 36. 39. 85. 90. 93.] 2720
2426 : [34. 36. 39. 86. 90. 93.] 2720
2427 : [34. 36. 52. 85. 86. 90.] 2528
2428 : [34. 36. 53. 59. 85. 86.] 2736
2429 : [34. 36. 53. 59. 85. 90.] 2736
2430 : [34. 36. 53. 59. 86. 90.] 2736
2431 : [34. 36. 53. 63. 85. 86.] 2736
2432 : [34. 36. 53. 63. 85. 90.] 2736
2433 : [34. 36. 53. 63. 86. 90.] 2736
2434 : [34. 36. 53. 85. 86. 90.] 3744
2435 : [ 34.  36.  53.  85.  86. 110.] 2736
2436 :

2614 : [23. 34. 36. 39. 59. 86. 93.] 2680
2615 : [23. 34. 36. 39. 59. 90. 93.] 2576
2616 : [23. 34. 36. 39. 63. 85. 86.] 2680
2617 : [23. 34. 36. 39. 63. 85. 93.] 2488
2618 : [23. 34. 36. 39. 63. 86. 93.] 2488
2619 : [23. 34. 36. 39. 85. 86. 90.] 2720
2620 : [23. 34. 36. 39. 85. 86. 93.] 2824
2621 : [23. 34. 36. 39. 85. 90. 93.] 2720
2622 : [23. 34. 36. 39. 86. 90. 93.] 2720
2623 : [23. 34. 36. 59. 63. 85. 86.] 2864
2624 : [23. 34. 36. 59. 63. 85. 90.] 2568
2625 : [23. 34. 36. 59. 63. 85. 93.] 2672
2626 : [23. 34. 36. 59. 63. 86. 90.] 2568
2627 : [23. 34. 36. 59. 63. 86. 93.] 2672
2628 : [23. 34. 36. 59. 63. 90. 93.] 2568
2629 : [23. 34. 36. 59. 85. 86. 90.] 2832
2630 : [23. 34. 36. 59. 85. 86. 93.] 2936
2631 : [23. 34. 36. 59. 85. 90. 93.] 2832
2632 : [23. 34. 36. 59. 86. 90. 93.] 2832
2633 : [23. 34. 36. 63. 85. 86. 90.] 2640
2634 : [23. 34. 36. 63. 85. 86. 93.] 2744
2635 : [23. 34. 36. 63. 85. 90. 93.] 2640
2636 : [23. 34. 36. 63. 86. 90. 93.] 2640
2637 : [23. 34. 36. 85. 86. 90. 93