In [102]:

dataset = []

with open("mushroom") as fp:  
    line = fp.readline().split(" ")[:-1]
    cnt = 1
    while line:
        line = list(map(int, line))
        line.sort()
        dataset.append(line)
        line = fp.readline().split(" ")[:-1]
        #print("\n")
        
        cnt += 1


In [103]:
import time
start_time = time.time()

global number
number = 0
min_sup = int(cnt * .5)


# _end = '-'

# def make_trie(words):
#     #print(words)
#     root = dict()
#     for i in range(len(words)):
#         #print("word",words[i])
#         current_dict = root
#         for letter in words[i]:
#             current_dict = current_dict.setdefault(letter, {})
#         current_dict[_end] = _end
#     return root

# def in_trie(trie, word):
#     current_dict = trie
#     for letter in word:
#         if letter in current_dict:
#             current_dict = current_dict[letter]
#         else:
#             return False
#     else:
#         if _end in current_dict:
#             return True
#         else:
#             return False

In [104]:
_end = '-'
val=1
def make_trie(words):
    #print(words)
    root = dict()
    for i in range(len(words)):
        #print("word",words[i])
        current_dict = root
        for letter in words[i]:
            current_dict = current_dict.setdefault(letter, {})
        
        #print("ccurrd",current_dict)
        
        if bool(current_dict):
            current_dict[_end] += 1
        else:
            current_dict[_end] = val
        
        #print("curr",current_dict[_end])
    return root


def in_trie(trie, word):
    current_dict = trie
    for letter in word:
        if letter in current_dict:
            current_dict = current_dict[letter]
        else:
            return 0
    else:
        if _end in current_dict:
            return current_dict[_end]
        else:
            return 0
        
        
global gtrie
gtrie = make_trie(dataset)

In [105]:
def isFreq(temp):
    #print("tempu",temp)
    temp =np.asarray(temp)
    pp = 0
    for i in range(len(data)):
        cc = 0
        for j in range(len(temp)):
            #print("aslkh",temp[j],data[i])
            if temp[j] in data[i]:
                cc+=1
            else:
                break
            
        if cc==len(temp):
            #print("Matched: ",data[i])
            pp+=1
        
    return pp

In [106]:
def join(l1):
    res = []
    for i in range(len(l1)):
        for k in range(len(l1)):
            if i>=k:
                continue
            if set(l1[i][0:(len(l1[i])-1)]) == set(l1[k][0:len(l1[k])-1]):
                new = l1[i]
                new = np.append(new,l1[k][len(l1[k])-1])
                #print()
                res.append(new)
        
    return res
    

In [107]:

from itertools import chain
import numpy as np

i=0
j=0
#data = [['1','2','5'],['2','4'],['2','3'],['1','2','4'],['1','3'],['2','3'],['1','3'],['1','2','3','5'],['1','2','3']]
#data = [[1,2,5],[2,4],[2,3],[1,2,4],[1,3],[2,3],[1,3],[1,2,3,5],[1,2,3]]
data = dataset
data = np.asarray(data)

print("data",data)



flat = list(chain.from_iterable(data))
ar = np.reshape(np.asarray(np.unique(flat)),(-1,1))


data [[  1   3   9 ...  98 107 113]
 [  2   3   9 ...  99 108 114]
 [  2   4   9 ...  99 108 115]
 ...
 [  2   6   9 ... 106 112 119]
 [  1   7  10 ... 102 110 119]
 [  2   3   9 ... 104 112 119]]


In [108]:
import itertools
def genItem(tempres,tempcnt):
    temp = np.asarray(join(tempres))
    print("Joining",len(temp))
    
    trie = make_trie(temp)
    #ALL ITEM GENERATED
    global number
    res = []
    cnt = []
    
    res_ =[]
    
    exist = 0

    for i in range(len(temp)):
        pruneitem = np.array(list(itertools.combinations(temp[i],len(temp[i])-1)))
        #pruneitem = pruneitem[len(pruneitem)-1]
        exist = 0
        
        for y in range(len(pruneitem)):
            if in_trie(trie,pruneitem[y])>0:
                exist+=1
            if exist < len(pruneitem):
                continue                
            res_.append(temp[i])
            
        freq = isFreq(temp[i])
        #print(freq)
        if freq<min_sup:
            continue
        
        number+=1
        #print(number,":",temp[i],freq)
        res.append(temp[i])
        cnt.append(freq)
        
    print("Pruning",len(res_))
    print("FP",len(res))
    return np.asarray(res),cnt


In [109]:
#print(len(ar))

In [110]:
number=0
arcnt = []

ln = len(ar)
index = []

#1-ITEM GENERATION
print("1-Itemset")
print("Joining ",len(ar))
print("Pruning  ",len(ar))


for i in range(ln):
    c=0
    for j in range(len(data)):
        if ar[i] in data[j]:
            c+=1
    
    if c<min_sup:
        #print("delete",i)
        index.append(i)
        ln-=1
        continue
        
    arcnt.append(c)

ar = np.delete(ar,index,0)    
# for i in range(len(ar)):
#     number+=1
#     print(number,":",ar[i],arcnt[i])


print("FP ",len(ar))
    
#2-ITEM GENERATION
cnt1 = []
res1 = []



res_ =[]
resp_ = []

global number
#print("ar",ar)
for i in range(len(ar)):
        for k in range(len(ar)):
            if i>=k:
                continue
            
            new2 = np.asarray([])
            new2 = np.append(new2,ar[i])
            new2 = np.append(new2,ar[k])
            
            res_.append(new2)
            
            if (ar[i] in ar) and (ar[k] in ar): 
                new = np.asarray([])
                new = np.append(new,ar[i])
                new = np.append(new,ar[k])
                
                resp_.append(new)

                itemFreq = isFreq(new)

                if itemFreq<min_sup:
                    continue
                number+=1
                #print(number,":",new,itemFreq)
                res1.append(new)
                cnt1.append(itemFreq)
    
    
    
print("2-Itemset")
print("Joining ",len(res_))
print("Pruning  ",len(resp_))
print("FP ",len(res1))

# >2-ITEM GENERATION
res1 = np.asarray(res1)

fixres = res1
fixcount = cnt1

locres = res1
loccnt = cnt1

itemc = 2

while True:
    itemc+=1
    print(itemc,"-Itemset")
    #trie = make_trie(locres)
    locres,loccnt = genItem(locres,loccnt)
    if len(locres)==0:
        print("FINISHED")
        break
print("--- %s seconds ---" % (time.time() - start_time))


1-Itemset
Joining  119
Pruning   119
FP  13
2-Itemset
Joining  78
Pruning   78
FP  41
3 -Itemset
Joining 84
Pruning 0
FP 56
4 -Itemset
Joining 40
Pruning 0
FP 35
5 -Itemset
Joining 10
Pruning 0
FP 8
6 -Itemset
Joining 0
Pruning 0
FP 0
FINISHED
--- 80.83238959312439 seconds ---
