In [81]:

dataset = []

with open("chess") as fp:  
    line = fp.readline().split(" ")[:-1]
    cnt = 1
    while line:
        print(line)
        line = list(map(int, line))
        dataset.append(line)
        line = fp.readline().split(" ")[:-1]
        print("\n")
        
        cnt += 1
        
min_sup = int(cnt * .4)


['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '12', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '12', '13', '16', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '11', '13', '15', '17', '20', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '44', '47', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42'


['1', '3', '5', '7', '9', '11', '14', '16', '18', '20', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '47', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '12', '14', '16', '18', '20', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '47', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '12', '14', '16', '18', '20', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '51', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '11', '14', '16', '18', '20', '21', '24', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '11', '14', '16', '18', '20', '21', '24', '25', '28', '29', '31', '34', '36', '38', '40', '42


['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '45', '46', '48', '50', '52', '55', '56', '58', '60', '62', '64', '66', '69', '70', '72', '75']


['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '45', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '68', '70', '72', '75']


['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '45', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '69', '70', '72', '75']


['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '45', '46', '48', '50', '52', '55', '56', '58', '60', '62', '64', '66', '68', '71', '72', '75']


['1', '3', '5', '7', '9', '12', '13', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42

['2', '3', '5', '7', '9', '11', '13', '15', '17', '20', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '47', '48', '51', '52', '54', '56', '58', '60', '62', '64', '66', '69', '70', '72', '75']


['2', '3', '5', '7', '9', '11', '14', '15', '17', '19', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '69', '70', '72', '75']


['2', '3', '5', '7', '9', '11', '14', '16', '17', '19', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '69', '70', '72', '75']


['2', '3', '5', '7', '9', '12', '14', '16', '17', '19', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '69', '70', '72', '75']


['2', '3', '5', '7', '9', '11', '14', '15', '17', '20', '21', '23', '25', '28', '29', '31', '34', '36', '38', '40', '42'

['1', '4', '5', '7', '9', '12', '13', '16', '18', '20', '21', '24', '25', '28', '29', '33', '34', '36', '38', '40', '42', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '4', '5', '7', '9', '11', '13', '16', '18', '20', '21', '24', '25', '28', '29', '31', '34', '36', '38', '40', '42', '44', '46', '48', '51', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '11', '13', '15', '17', '19', '21', '24', '25', '28', '29', '31', '34', '37', '38', '40', '42', '44', '46', '49', '51', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '11', '13', '15', '17', '20', '21', '24', '25', '28', '29', '31', '34', '37', '38', '40', '42', '44', '47', '49', '50', '52', '54', '56', '58', '60', '62', '64', '66', '68', '70', '72', '74']


['1', '3', '5', '7', '9', '12', '14', '16', '17', '20', '21', '24', '25', '28', '29', '33', '34', '36', '38', '40', '42'


['1', '3', '5', '7', '9', '12', '14', '16', '17', '20', '21', '23', '25', '27', '29', '31', '34', '36', '38', '40', '42', '44', '47', '48', '50', '52', '55', '56', '58', '60', '62', '64', '66', '68', '71', '72', '75']


['1', '3', '5', '8', '9', '11', '14', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '44', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '68', '71', '72', '75']


['1', '3', '5', '7', '10', '11', '14', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '44', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '68', '71', '72', '75']


['1', '3', '5', '7', '10', '12', '14', '15', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '44', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '68', '71', '72', '75']


['1', '3', '5', '8', '9', '12', '14', '16', '17', '19', '21', '23', '25', '27', '29', '31', '34', '36', '39', '40', '



['2', '3', '5', '7', '9', '12', '13', '16', '17', '19', '22', '24', '25', '27', '29', '32', '34', '36', '38', '40', '43', '44', '46', '48', '50', '52', '54', '56', '58', '60', '62', '64', '66', '69', '70', '73', '74']


['2', '3', '5', '7', '9', '11', '13', '15', '17', '19', '22', '23', '25', '27', '29', '31', '34', '36', '38', '40', '43', '44', '46', '48', '51', '52', '54', '56', '58', '60', '62', '64', '67', '68', '70', '73', '74']


['2', '3', '6', '7', '10', '11', '13', '15', '17', '19', '22', '23', '25', '27', '29', '31', '35', '36', '38', '40', '43', '44', '46', '48', '51', '52', '54', '56', '58', '60', '62', '64', '67', '68', '70', '73', '74']


['2', '3', '5', '7', '9', '11', '13', '16', '17', '19', '22', '23', '25', '27', '29', '31', '34', '36', '38', '40', '43', '44', '46', '48', '51', '52', '54', '56', '58', '60', '62', '64', '67', '68', '70', '73', '74']


['2', '3', '6', '7', '9', '11', '13', '15', '17', '19', '22', '23', '25', '27', '29', '31', '35', '36', '38', '40', '

['2', '3', '5', '7', '10', '11', '13', '16', '18', '20', '22', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '44', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '69', '71', '72', '75']


['2', '3', '5', '8', '9', '12', '13', '16', '18', '20', '22', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '44', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '69', '71', '72', '75']


['2', '3', '5', '7', '10', '12', '13', '16', '18', '20', '22', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '44', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '69', '71', '72', '75']


['2', '3', '5', '8', '9', '11', '13', '16', '18', '20', '22', '23', '25', '27', '29', '31', '34', '36', '39', '40', '42', '44', '46', '48', '51', '52', '55', '56', '58', '60', '62', '64', '66', '68', '71', '72', '75']


['2', '3', '5', '7', '10', '11', '13', '16', '18', '20', '22', '23', '25', '27', '29', '31', '34', '36', '39', '40', '



['2', '4', '5', '8', '9', '11', '13', '16', '17', '19', '21', '23', '26', '27', '30', '33', '35', '36', '38', '40', '42', '44', '46', '48', '51', '52', '54', '56', '58', '61', '62', '64', '67', '68', '71', '73', '74']


['2', '4', '5', '8', '9', '11', '13', '16', '17', '19', '21', '23', '26', '27', '30', '31', '35', '36', '38', '40', '42', '44', '46', '48', '51', '52', '54', '56', '58', '61', '62', '64', '67', '68', '71', '73', '74']




In [ ]:
min_sup
cnt

In [83]:
def isFreq(temp):
    #print("tempu",temp)
    temp =np.asarray(temp)
    pp = 0
    for i in range(len(data)):
        cc = 0
        for j in range(len(temp)):
            #print("aslkh",temp[j],data[i])
            if temp[j] in data[i]:
                cc+=1
            else:
                break
            
        if cc==len(temp):
            #print("Matched: ",data[i])
            pp+=1
        
    return pp

In [84]:
def join(l1):
    res = []
    for i in range(len(l1)):
        for k in range(len(l1)):
            if i>=k:
                continue
            if set(l1[i][0:(len(l1[i])-1)]) == set(l1[k][0:len(l1[k])-1]):
                new = l1[i]
                new = np.append(new,l1[k][len(l1[k])-1])
                #print()
                res.append(new)
        
    return res
    

In [85]:

from itertools import chain
import numpy as np

i=0
j=0
#data = [['1','2','5'],['2','4'],['2','3'],['1','2','4'],['1','3'],['2','3'],['1','3'],['1','2','3','5'],['1','2','3']]
#data = [[1,2,5],[2,4],[2,3],[1,2,4],[1,3],[2,3],[1,3],[1,2,3,5],[1,2,3]]
data = dataset
data = np.asarray(data)

print("data",data)



flat = list(chain.from_iterable(data))
ar = np.reshape(np.asarray(np.unique(flat)),(-1,1))


data [[ 1  3  5 ... 70 72 74]
 [ 1  3  5 ... 70 72 74]
 [ 1  3  5 ... 70 72 74]
 ...
 [ 2  4  5 ... 70 73 74]
 [ 2  4  5 ... 71 73 74]
 [ 2  4  5 ... 71 73 74]]


In [86]:
print(len(ar))

75


In [90]:
arcnt = []
print(type(ar))

    
i=0
j=0

for ii in range(len(ar)):
    c=0
    for jj in range(len(data)):
        if ar[ii] in data[jj]:
            c+=1
    
    if c<min_sup:
        ar = np.delete(ar,ii,0)
        continue
    arcnt.append(c)


print(ar)
print(arcnt)

print(len(ar))

<class 'numpy.ndarray'>
[[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [14]
 [15]
 [17]
 [19]
 [21]
 [23]
 [24]
 [25]
 [27]
 [29]
 [31]
 [34]
 [36]
 [38]
 [40]
 [42]
 [44]
 [46]
 [48]
 [50]
 [52]
 [54]
 [56]
 [58]
 [60]
 [62]
 [64]
 [66]
 [68]
 [70]
 [72]
 [74]]
[1669, 1527, 2839, 2971, 3076, 2874, 2129, 1722, 1474, 2026, 2500, 1980, 2225, 1817, 1379, 2860, 2205, 3181, 2526, 3040, 3099, 2196, 3170, 2714, 2612, 2556, 3013, 1975, 3185, 2216, 3021, 3195, 3149, 3060, 2631, 3021, 1984, 2007, 2345, 2407]
40


In [91]:
#def prune(arr):

In [92]:
import itertools

def genItem(tempres,tempcnt):
    temp = np.asarray(join(tempres))
    #ALL ITEM GENERATED
    
    res = []
    cnt = []
    
    exist = 0
    
    #print("temmmmmp",temp,"end")
    
    for i in range(len(temp)):
        pruneitem = np.array(list(itertools.combinations(temp[i],len(temp[i])-1)))
        #pruneitem = pruneitem[len(pruneitem)-1]
        exist = 0
        for y in range(len(pruneitem)):
            for x in range(len(temp)):
                c = 0
                for j in range(len(pruneitem[y])):
                    if pruneitem[y][j] in temp[x]:
                        c+=1
                    else:
                        break

                if c==len(pruneitem[y]):
                    exist+=1
                    break
            if exist < len(pruneitem):
                continue
        
        freq = isFreq(temp[i])
        print(freq)
        if freq<min_sup:
            continue
            
        print(temp[i],freq)
        res.append(temp[i])
        cnt.append(freq)
        
    return np.asarray(res),cnt


In [ ]:
cnt1 = []
res1 = []

print("ar",ar)

for i in range(len(ar)):
        for k in range(len(ar)):
            if i>=k:
                continue
                
            #print(ar[i],ar[k])
            
            if (ar[i] in ar) and (ar[k] in ar): 
                new = np.asarray([])
                new = np.append(new,ar[i])
                new = np.append(new,ar[k])


                itemFreq = isFreq(new)
                #print(itemFreq)

                if itemFreq<min_sup:
                    continue
                print(new,itemFreq)
                res1.append(new)
                cnt1.append(itemFreq)
                        
            
            
            
res1 = np.asarray(res1)
print("res1",res1)
print("cnt1",cnt1)

fixres = res1
fixcount = cnt1

locres = res1
loccnt = cnt1
while True:
    print("sa")
    locres,loccnt = genItem(locres,loccnt)
    print("ITEMSET")
    print(locres)
    print("COUNT")
    print(loccnt)
    if len(locres)==0:
        break



ar [[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [14]
 [15]
 [17]
 [19]
 [21]
 [23]
 [24]
 [25]
 [27]
 [29]
 [31]
 [34]
 [36]
 [38]
 [40]
 [42]
 [44]
 [46]
 [48]
 [50]
 [52]
 [54]
 [56]
 [58]
 [60]
 [62]
 [64]
 [66]
 [68]
 [70]
 [72]
 [74]]
[1. 3.] 1482
[1. 5.] 1550
[1. 7.] 1634
[1. 9.] 1507
[ 1. 17.] 1459
[ 1. 21.] 1441
[ 1. 25.] 1486
[ 1. 29.] 1669
[ 1. 34.] 1642
[ 1. 36.] 1615
[ 1. 40.] 1651
[ 1. 42.] 1413
[ 1. 48.] 1606
[ 1. 52.] 1667
[ 1. 56.] 1625
[ 1. 58.] 1669
[ 1. 60.] 1669
[ 1. 62.] 1585
[ 1. 64.] 1297
[ 1. 66.] 1649
[ 1. 68.] 1319
[ 1. 72.] 1328
[2. 3.] 1357
[2. 5.] 1421
[2. 7.] 1442
[2. 9.] 1367
[ 2. 25.] 1374
[ 2. 29.] 1512
[ 2. 31.] 1284
[ 2. 34.] 1398
[ 2. 36.] 1484
[ 2. 40.] 1519
[ 2. 42.] 1301
[ 2. 44.] 1527
[ 2. 46.] 1286
[ 2. 48.] 1407
[ 2. 52.] 1518
[ 2. 56.] 1396
[ 2. 58.] 1526
[ 2. 60.] 1480
[ 2. 62.] 1475
[ 2. 64.] 1334
[ 2. 66.] 1372
[3. 5.] 2639
[3. 7.] 2765
[3. 9.] 2571
[ 3. 11.] 1909
[ 3. 13.] 1513
[ 3. 14.] 1326
[ 3. 15.] 1857
[ 3. 17.] 2272
[ 3. 19.] 178

[40. 68.] 1964
[40. 70.] 2007
[40. 72.] 2335
[40. 74.] 2381
[42. 44.] 2250
[42. 46.] 2220
[42. 48.] 2564
[42. 50.] 1655
[42. 52.] 2708
[42. 54.] 1734
[42. 56.] 2570
[42. 58.] 2713
[42. 60.] 2688
[42. 62.] 2598
[42. 64.] 2464
[42. 66.] 2612
[42. 68.] 1678
[42. 70.] 1741
[42. 72.] 2193
[42. 74.] 1925
[44. 46.] 2114
[44. 48.] 2439
[44. 50.] 1592
[44. 52.] 2601
[44. 54.] 1880
[44. 56.] 2471
[44. 58.] 2611
[44. 60.] 2565
[44. 62.] 2522
[44. 64.] 2211
[44. 66.] 2454
[44. 68.] 1704
[44. 70.] 1665
[44. 72.] 1874
[44. 74.] 2026
[46. 48.] 2404
[46. 50.] 1533
[46. 52.] 2545
[46. 54.] 1797
[46. 56.] 2405
[46. 58.] 2555
[46. 60.] 2517
[46. 62.] 2449
[46. 64.] 2145
[46. 66.] 2425
[46. 68.] 1559
[46. 70.] 1513
[46. 72.] 1891
[46. 74.] 1925
[48. 50.] 1824
[48. 52.] 3002
[48. 54.] 2064
[48. 56.] 2838
[48. 58.] 3012
[48. 60.] 2986
[48. 62.] 2877
[48. 64.] 2478
[48. 66.] 2873
[48. 68.] 1837
[48. 70.] 1838
[48. 72.] 2231
[48. 74.] 2234
[50. 52.] 1970
[50. 54.] 1381
[50. 56.] 1881
[50. 58.] 1975
[50. 60.] 

1397
[ 1. 21. 36.] 1397
1423
[ 1. 21. 40.] 1423
1229
1388
[ 1. 21. 48.] 1388
1439
[ 1. 21. 52.] 1439
1410
[ 1. 21. 56.] 1410
1441
[ 1. 21. 58.] 1441
1441
[ 1. 21. 60.] 1441
1361
[ 1. 21. 62.] 1361
1108
1429
[ 1. 21. 66.] 1429
1207
1128
1486
[ 1. 25. 29.] 1486
1461
[ 1. 25. 34.] 1461
1454
[ 1. 25. 36.] 1454
1468
[ 1. 25. 40.] 1468
1245
1448
[ 1. 25. 48.] 1448
1484
[ 1. 25. 52.] 1484
1447
[ 1. 25. 56.] 1447
1486
[ 1. 25. 58.] 1486
1486
[ 1. 25. 60.] 1486
1412
[ 1. 25. 62.] 1412
1130
1468
[ 1. 25. 66.] 1468
1186
1174
1642
[ 1. 29. 34.] 1642
1615
[ 1. 29. 36.] 1615
1651
[ 1. 29. 40.] 1651
1413
[ 1. 29. 42.] 1413
1606
[ 1. 29. 48.] 1606
1667
[ 1. 29. 52.] 1667
1625
[ 1. 29. 56.] 1625
1669
[ 1. 29. 58.] 1669
1669
[ 1. 29. 60.] 1669
1585
[ 1. 29. 62.] 1585
1297
[ 1. 29. 64.] 1297
1649
[ 1. 29. 66.] 1649
1319
[ 1. 29. 68.] 1319
1328
[ 1. 29. 72.] 1328
1588
[ 1. 34. 36.] 1588
1624
[ 1. 34. 40.] 1624
1404
[ 1. 34. 42.] 1404
1579
[ 1. 34. 48.] 1579
1640
[ 1. 34. 52.] 1640
1602
[ 1. 34. 56.] 1602


2128
[ 3.  9. 31.] 2128
2466
[ 3.  9. 34.] 2466
2478
[ 3.  9. 36.] 2478
1773
[ 3.  9. 38.] 1773
2549
[ 3.  9. 40.] 2549
2187
[ 3.  9. 42.] 2187
2059
[ 3.  9. 44.] 2059
2015
[ 3.  9. 46.] 2015
2404
[ 3.  9. 48.] 2404
1643
[ 3.  9. 50.] 1643
2565
[ 3.  9. 52.] 2565
1704
[ 3.  9. 54.] 1704
2471
[ 3.  9. 56.] 2471
2571
[ 3.  9. 58.] 2571
2545
[ 3.  9. 60.] 2545
2468
[ 3.  9. 62.] 2468
2129
[ 3.  9. 64.] 2129
2448
[ 3.  9. 66.] 2448
1545
[ 3.  9. 68.] 1545
1755
[ 3.  9. 70.] 1755
1944
[ 3.  9. 72.] 1944
1883
[ 3.  9. 74.] 1883
1031
878
1490
[ 3. 11. 15.] 1490
1653
[ 3. 11. 17.] 1653
1303
[ 3. 11. 19.] 1303
1282
[ 3. 11. 21.] 1282
1104
1594
[ 3. 11. 25.] 1594
1384
[ 3. 11. 27.] 1384
1909
[ 3. 11. 29.] 1909
1546
[ 3. 11. 31.] 1546
1806
[ 3. 11. 34.] 1806
1816
[ 3. 11. 36.] 1816
1293
[ 3. 11. 38.] 1293
1883
[ 3. 11. 40.] 1883
1559
[ 3. 11. 42.] 1559
1490
[ 3. 11. 44.] 1490
1506
[ 3. 11. 46.] 1506
1742
[ 3. 11. 48.] 1742
1184
1900
[ 3. 11. 52.] 1900
1340
[ 3. 11. 54.] 1340
1847
[ 3. 11. 56.] 18

2813
[ 3. 40. 58.] 2813
2780
[ 3. 40. 60.] 2780
2709
[ 3. 40. 62.] 2709
2352
[ 3. 40. 64.] 2352
2679
[ 3. 40. 66.] 2679
1689
[ 3. 40. 68.] 1689
1845
[ 3. 40. 70.] 1845
2165
[ 3. 40. 72.] 2165
2024
[ 3. 40. 74.] 2024
1959
[ 3. 42. 44.] 1959
1962
[ 3. 42. 46.] 1962
2277
[ 3. 42. 48.] 2277
1503
[ 3. 42. 50.] 1503
2406
[ 3. 42. 52.] 2406
1431
[ 3. 42. 54.] 1431
2299
[ 3. 42. 56.] 2299
2411
[ 3. 42. 58.] 2411
2398
[ 3. 42. 60.] 2398
2313
[ 3. 42. 62.] 2313
2217
[ 3. 42. 64.] 2217
2344
[ 3. 42. 66.] 2344
1440
[ 3. 42. 68.] 1440
1595
[ 3. 42. 70.] 1595
2039
[ 3. 42. 72.] 2039
1622
[ 3. 42. 74.] 1622
1819
[ 3. 44. 46.] 1819
2111
[ 3. 44. 48.] 2111
1423
[ 3. 44. 50.] 1423
2259
[ 3. 44. 52.] 2259
1536
[ 3. 44. 54.] 1536
2163
[ 3. 44. 56.] 2163
2268
[ 3. 44. 58.] 2268
2234
[ 3. 44. 60.] 2234
2199
[ 3. 44. 62.] 2199
1933
[ 3. 44. 64.] 1933
2149
[ 3. 44. 66.] 2149
1433
[ 3. 44. 68.] 1433
1506
[ 3. 44. 70.] 1506
1710
[ 3. 44. 72.] 1710
1682
[ 3. 44. 74.] 1682
2115
[ 3. 46. 48.] 2115
1396
[ 3. 46. 50

902
1855
[ 5. 21. 25.] 1855
1455
[ 5. 21. 27.] 1455
2082
[ 5. 21. 29.] 2082
1656
[ 5. 21. 31.] 1656
2027
[ 5. 21. 34.] 2027
2035
[ 5. 21. 36.] 2035
1410
[ 5. 21. 38.] 1410
2068
[ 5. 21. 40.] 2068
1799
[ 5. 21. 42.] 1799
1791
[ 5. 21. 44.] 1791
1540
[ 5. 21. 46.] 1540
1961
[ 5. 21. 48.] 1961
1219
2079
[ 5. 21. 52.] 2079
1443
[ 5. 21. 54.] 1443
1952
[ 5. 21. 56.] 1952
2088
[ 5. 21. 58.] 2088
2046
[ 5. 21. 60.] 2046
1983
[ 5. 21. 62.] 1983
1678
[ 5. 21. 64.] 1678
1983
[ 5. 21. 66.] 1983
1381
[ 5. 21. 68.] 1381
1320
[ 5. 21. 70.] 1320
1500
[ 5. 21. 72.] 1500
1590
[ 5. 21. 74.] 1590
0
1459
[ 5. 23. 25.] 1459
1017
1684
[ 5. 23. 29.] 1684
1631
[ 5. 23. 31.] 1631
1640
[ 5. 23. 34.] 1640
1652
[ 5. 23. 36.] 1652
1216
1686
[ 5. 23. 40.] 1686
1635
[ 5. 23. 42.] 1635
1348
[ 5. 23. 44.] 1348
1364
[ 5. 23. 46.] 1364
1595
[ 5. 23. 48.] 1595
1034
1687
[ 5. 23. 52.] 1687
782
1579
[ 5. 23. 56.] 1579
1687
[ 5. 23. 58.] 1687
1640
[ 5. 23. 60.] 1640
1603
[ 5. 23. 62.] 1603
1668
[ 5. 23. 64.] 1668
1548
[ 5. 

2204
[ 5. 66. 72.] 2204
2101
[ 5. 66. 74.] 2101
1274
1383
[ 5. 68. 72.] 1383
1486
[ 5. 68. 74.] 1486
1448
[ 5. 70. 72.] 1448
1515
[ 5. 70. 74.] 1515
1473
[ 5. 72. 74.] 1473
1896
[ 7.  9. 11.] 1896
1591
[ 7.  9. 13.] 1591
1164
1773
[ 7.  9. 15.] 1773
2202
[ 7.  9. 17.] 2202
1706
[ 7.  9. 19.] 1706
1928
[ 7.  9. 21.] 1928
1551
[ 7.  9. 23.] 1551
1204
2427
[ 7.  9. 25.] 2427
1923
[ 7.  9. 27.] 1923
2755
[ 7.  9. 29.] 2755
2179
[ 7.  9. 31.] 2179
2644
[ 7.  9. 34.] 2644
2658
[ 7.  9. 36.] 2658
1945
[ 7.  9. 38.] 1945
2733
[ 7.  9. 40.] 2733
2336
[ 7.  9. 42.] 2336
2242
[ 7.  9. 44.] 2242
2147
[ 7.  9. 46.] 2147
2572
[ 7.  9. 48.] 2572
1806
[ 7.  9. 50.] 1806
2747
[ 7.  9. 52.] 2747
1922
[ 7.  9. 54.] 1922
2651
[ 7.  9. 56.] 2651
2754
[ 7.  9. 58.] 2754
2718
[ 7.  9. 60.] 2718
2631
[ 7.  9. 62.] 2631
2253
[ 7.  9. 64.] 2253
2601
[ 7.  9. 66.] 2601
1727
[ 7.  9. 68.] 1727
1901
[ 7.  9. 70.] 1901
1987
[ 7.  9. 72.] 1987
2100
[ 7.  9. 74.] 2100
1137
913
1590
[ 7. 11. 15.] 1590
1769
[ 7. 11. 17

2426
[ 7. 34. 64.] 2426
2777
[ 7. 34. 66.] 2777
1874
[ 7. 34. 68.] 1874
1953
[ 7. 34. 70.] 1953
2168
[ 7. 34. 72.] 2168
2214
[ 7. 34. 74.] 2214
2033
[ 7. 36. 38.] 2033
2953
[ 7. 36. 40.] 2953
2515
[ 7. 36. 42.] 2515
2413
[ 7. 36. 44.] 2413
2353
[ 7. 36. 46.] 2353
2867
[ 7. 36. 48.] 2867
1899
[ 7. 36. 50.] 1899
2968
[ 7. 36. 52.] 2968
2058
[ 7. 36. 54.] 2058
2822
[ 7. 36. 56.] 2822
2978
[ 7. 36. 58.] 2978
2934
[ 7. 36. 60.] 2934
2843
[ 7. 36. 62.] 2843
2438
[ 7. 36. 64.] 2438
2809
[ 7. 36. 66.] 2809
1843
[ 7. 36. 68.] 1843
1899
[ 7. 36. 70.] 1899
2154
[ 7. 36. 72.] 2154
2232
[ 7. 36. 74.] 2232
2124
[ 7. 38. 40.] 2124
1858
[ 7. 38. 42.] 1858
1843
[ 7. 38. 44.] 1843
1630
[ 7. 38. 46.] 1630
1955
[ 7. 38. 48.] 1955
1452
[ 7. 38. 50.] 1452
2117
[ 7. 38. 52.] 2117
1487
[ 7. 38. 54.] 1487
2037
[ 7. 38. 56.] 2037
2123
[ 7. 38. 58.] 2123
2089
[ 7. 38. 60.] 2089
2078
[ 7. 38. 62.] 2078
1829
[ 7. 38. 64.] 1829
2004
[ 7. 38. 66.] 2004
1365
[ 7. 38. 68.] 1365
1786
[ 7. 38. 70.] 1786
1581
[ 7. 38. 72

1561
[ 9. 23. 31.] 1561
1555
[ 9. 23. 34.] 1555
1587
[ 9. 23. 36.] 1587
1139
1621
[ 9. 23. 40.] 1621
1561
[ 9. 23. 42.] 1561
1276
1285
[ 9. 23. 46.] 1285
1530
[ 9. 23. 48.] 1530
1011
1622
[ 9. 23. 52.] 1622
755
1536
[ 9. 23. 56.] 1536
1622
[ 9. 23. 58.] 1622
1583
[ 9. 23. 60.] 1583
1536
[ 9. 23. 62.] 1536
1583
[ 9. 23. 64.] 1583
1463
[ 9. 23. 66.] 1463
942
1087
1463
[ 9. 23. 72.] 1463
934
1770
[ 9. 25. 27.] 1770
2537
[ 9. 25. 29.] 2537
1971
[ 9. 25. 31.] 1971
2429
[ 9. 25. 34.] 2429
2477
[ 9. 25. 36.] 2477
1771
[ 9. 25. 38.] 1771
2521
[ 9. 25. 40.] 2521
2152
[ 9. 25. 42.] 2152
2097
[ 9. 25. 44.] 2097
2014
[ 9. 25. 46.] 2014
2432
[ 9. 25. 48.] 2432
1570
[ 9. 25. 50.] 1570
2536
[ 9. 25. 52.] 2536
1799
[ 9. 25. 54.] 1799
2433
[ 9. 25. 56.] 2433
2542
[ 9. 25. 58.] 2542
2520
[ 9. 25. 60.] 2520
2433
[ 9. 25. 62.] 2433
2065
[ 9. 25. 64.] 2065
2409
[ 9. 25. 66.] 2409
1592
[ 9. 25. 68.] 1592
1645
[ 9. 25. 70.] 1645
1836
[ 9. 25. 72.] 1836
1949
[ 9. 25. 74.] 1949
1990
[ 9. 27. 29.] 1990
1483
[ 9

[11. 17. 54.] 1293
1748
[11. 17. 56.] 1748
1824
[11. 17. 58.] 1824
1789
[11. 17. 60.] 1789
1724
[11. 17. 62.] 1724
1384
[11. 17. 64.] 1384
1701
[11. 17. 66.] 1701
1138
1244
1312
[11. 17. 72.] 1312
1397
[11. 17. 74.] 1397
979
1243
1051
1461
[11. 19. 29.] 1461
1147
1395
[11. 19. 34.] 1395
1393
[11. 19. 36.] 1393
994
1451
[11. 19. 40.] 1451
1249
1162
1475
[11. 19. 46.] 1475
1339
[11. 19. 48.] 1339
1464
[11. 19. 52.] 1464
1078
1410
[11. 19. 56.] 1410
1474
[11. 19. 58.] 1474
1440
[11. 19. 60.] 1440
1391
[11. 19. 62.] 1391
1133
1366
[11. 19. 66.] 1366
917
964
1043
1144
1231
1078
1448
[11. 21. 29.] 1448
1132
1377
[11. 21. 34.] 1377
1409
[11. 21. 36.] 1409
968
1437
[11. 21. 40.] 1437
1198
1200
1067
1335
[11. 21. 48.] 1335
1453
[11. 21. 52.] 1453
1066
1385
[11. 21. 56.] 1385
1462
[11. 21. 58.] 1462
1427
[11. 21. 60.] 1427
1362
[11. 21. 62.] 1362
1075
1358
[11. 21. 66.] 1358
981
920
974
1148
1319
[11. 25. 27.] 1319
1788
[11. 25. 29.] 1788
1357
[11. 25. 31.] 1357
1684
[11. 25. 34.] 1684
1734
[11.

1612
[13. 40. 62.] 1612
1393
[13. 40. 64.] 1393
1538
[13. 40. 66.] 1538
1314
[13. 40. 74.] 1314
1165
1135
1301
[13. 42. 48.] 1301
1409
[13. 42. 52.] 1409
1334
[13. 42. 56.] 1334
1413
[13. 42. 58.] 1413
1388
[13. 42. 60.] 1388
1319
[13. 42. 62.] 1319
1276
1312
[13. 42. 66.] 1312
1017
1109
1260
1384
[13. 44. 52.] 1384
1313
[13. 44. 56.] 1313
1391
[13. 44. 58.] 1391
1345
[13. 44. 60.] 1345
1314
[13. 44. 62.] 1314
1167
1234
1101
1229
1336
[13. 46. 52.] 1336
1259
1343
[13. 46. 58.] 1343
1305
[13. 46. 60.] 1305
1253
1116
1213
1033
1575
[13. 48. 52.] 1575
1481
[13. 48. 56.] 1481
1582
[13. 48. 58.] 1582
1556
[13. 48. 60.] 1556
1473
[13. 48. 62.] 1473
1283
[13. 48. 64.] 1283
1443
[13. 48. 66.] 1443
1196
1615
[13. 52. 56.] 1615
1713
[13. 52. 58.] 1713
1667
[13. 52. 60.] 1667
1604
[13. 52. 62.] 1604
1393
[13. 52. 64.] 1393
1539
[13. 52. 66.] 1539
1317
[13. 52. 74.] 1317
1619
[13. 56. 58.] 1619
1573
[13. 56. 60.] 1573
1538
[13. 56. 62.] 1538
1310
[13. 56. 64.] 1310
1445
[13. 56. 66.] 1445
1296
[13

2014
[15. 52. 58.] 2014
2004
[15. 52. 60.] 2004
1889
[15. 52. 62.] 1889
1541
[15. 52. 64.] 1541
1910
[15. 52. 66.] 1910
1321
[15. 52. 70.] 1321
1518
[15. 52. 72.] 1518
1476
[15. 52. 74.] 1476
1284
[15. 54. 56.] 1284
1346
[15. 54. 58.] 1346
1336
[15. 54. 60.] 1336
1270
863
1242
877
839
1175
1896
[15. 56. 58.] 1896
1886
[15. 56. 60.] 1886
1805
[15. 56. 62.] 1805
1448
[15. 56. 64.] 1448
1792
[15. 56. 66.] 1792
1263
1415
[15. 56. 72.] 1415
1448
[15. 56. 74.] 1448
2014
[15. 58. 60.] 2014
1900
[15. 58. 62.] 1900
1541
[15. 58. 64.] 1541
1920
[15. 58. 66.] 1920
1326
[15. 58. 70.] 1326
1518
[15. 58. 72.] 1518
1486
[15. 58. 74.] 1486
1890
[15. 60. 62.] 1890
1531
[15. 60. 64.] 1531
1921
[15. 60. 66.] 1921
1319
[15. 60. 70.] 1319
1518
[15. 60. 72.] 1518
1476
[15. 60. 74.] 1476
1442
[15. 62. 64.] 1442
1802
[15. 62. 66.] 1802
1281
[15. 62. 70.] 1281
1426
[15. 62. 72.] 1426
1424
[15. 62. 74.] 1424
1472
[15. 64. 66.] 1472
1067
1333
[15. 64. 72.] 1333
1003
1257
1518
[15. 66. 72.] 1518
1382
[15. 66. 74.

1564
[17. 56. 68.] 1564
1590
[17. 56. 70.] 1590
1716
[17. 56. 72.] 1716
1830
[17. 56. 74.] 1830
2456
[17. 58. 60.] 2456
2368
[17. 58. 62.] 2368
1974
[17. 58. 64.] 1974
2348
[17. 58. 66.] 2348
1572
[17. 58. 68.] 1572
1654
[17. 58. 70.] 1654
1828
[17. 58. 72.] 1828
1874
[17. 58. 74.] 1874
2326
[17. 60. 62.] 2326
1932
[17. 60. 64.] 1932
2349
[17. 60. 66.] 2349
1530
[17. 60. 68.] 1530
1617
[17. 60. 70.] 1617
1828
[17. 60. 72.] 1828
1832
[17. 60. 74.] 1832
1870
[17. 62. 64.] 1870
2224
[17. 62. 66.] 2224
1520
[17. 62. 68.] 1520
1610
[17. 62. 70.] 1610
1731
[17. 62. 72.] 1731
1811
[17. 62. 74.] 1811
1859
[17. 64. 66.] 1859
1255
1379
[17. 64. 70.] 1379
1628
[17. 64. 72.] 1628
1350
[17. 64. 74.] 1350
1443
[17. 66. 68.] 1443
1542
[17. 66. 70.] 1542
1828
[17. 66. 72.] 1828
1724
[17. 66. 74.] 1724
1087
1146
1270
1222
1284
[17. 70. 74.] 1284
1203
1232
990
1363
[19. 21. 29.] 1363
1085
1304
[19. 21. 34.] 1304
1337
[19. 21. 36.] 1337
828
1353
[19. 21. 40.] 1353
1208
1163
1377
[19. 21. 46.] 1377
1290
[

1265
2161
[21. 36. 52.] 2161
1497
[21. 36. 54.] 1497
2027
[21. 36. 56.] 2027
2170
[21. 36. 58.] 2170
2128
[21. 36. 60.] 2128
2041
[21. 36. 62.] 2041
1718
[21. 36. 64.] 1718
2039
[21. 36. 66.] 2039
1424
[21. 36. 68.] 1424
1292
[21. 36. 70.] 1292
1519
[21. 36. 72.] 1519
1640
[21. 36. 74.] 1640
1451
[21. 38. 40.] 1451
1275
1322
[21. 38. 44.] 1322
994
1336
[21. 38. 48.] 1336
916
1445
[21. 38. 52.] 1445
997
1372
[21. 38. 56.] 1372
1450
[21. 38. 58.] 1450
1418
[21. 38. 60.] 1418
1406
[21. 38. 62.] 1406
1217
1357
[21. 38. 66.] 1357
1010
1203
1050
1142
1874
[21. 40. 42.] 1874
1843
[21. 40. 44.] 1843
1598
[21. 40. 46.] 1598
2071
[21. 40. 48.] 2071
1304
[21. 40. 50.] 1304
2189
[21. 40. 52.] 2189
1508
[21. 40. 54.] 1508
2056
[21. 40. 56.] 2056
2198
[21. 40. 58.] 2198
2157
[21. 40. 60.] 2157
2080
[21. 40. 62.] 2080
1754
[21. 40. 64.] 1754
2069
[21. 40. 66.] 2069
1447
[21. 40. 68.] 1447
1341
[21. 40. 70.] 1341
1558
[21. 40. 72.] 1558
1664
[21. 40. 74.] 1664
1611
[21. 42. 44.] 1611
1427
[21. 42. 46.

1288
[24. 48. 74.] 1288
1368
[24. 52. 54.] 1368
1307
[24. 52. 56.] 1307
1367
[24. 52. 58.] 1367
1368
[24. 52. 60.] 1368
1327
[24. 52. 62.] 1327
1368
[24. 52. 66.] 1368
1368
[24. 52. 74.] 1368
1312
[24. 54. 56.] 1312
1378
[24. 54. 58.] 1378
1379
[24. 54. 60.] 1379
1338
[24. 54. 62.] 1338
1379
[24. 54. 66.] 1379
1379
[24. 54. 74.] 1379
1311
[24. 56. 58.] 1311
1312
[24. 56. 60.] 1312
1280
[24. 56. 62.] 1280
1312
[24. 56. 66.] 1312
1312
[24. 56. 74.] 1312
1378
[24. 58. 60.] 1378
1338
[24. 58. 62.] 1338
1378
[24. 58. 66.] 1378
1378
[24. 58. 74.] 1378
1338
[24. 60. 62.] 1338
1379
[24. 60. 66.] 1379
1379
[24. 60. 74.] 1379
1338
[24. 62. 66.] 1338
1338
[24. 62. 74.] 1338
1379
[24. 66. 74.] 1379
1972
[25. 27. 29.] 1972
1447
[25. 27. 31.] 1447
1849
[25. 27. 34.] 1849
1953
[25. 27. 36.] 1953
1101
1950
[25. 27. 40.] 1950
1538
[25. 27. 42.] 1538
1556
[25. 27. 44.] 1556
1589
[25. 27. 46.] 1589
1938
[25. 27. 48.] 1938
1207
1966
[25. 27. 52.] 1966
1421
[25. 27. 54.] 1421
1861
[25. 27. 56.] 1861
1975
[

1958
[27. 34. 66.] 1958
1291
[27. 34. 68.] 1291
1432
[27. 34. 72.] 1432
1567
[27. 34. 74.] 1567
2133
[27. 36. 40.] 2133
1694
[27. 36. 42.] 1694
1685
[27. 36. 44.] 1685
1720
[27. 36. 46.] 1720
2111
[27. 36. 48.] 2111
1333
[27. 36. 50.] 1333
2148
[27. 36. 52.] 2148
1530
[27. 36. 54.] 1530
2036
[27. 36. 56.] 2036
2158
[27. 36. 58.] 2158
2124
[27. 36. 60.] 2124
2042
[27. 36. 62.] 2042
1614
[27. 36. 64.] 1614
2026
[27. 36. 66.] 2026
1299
[27. 36. 68.] 1299
1456
[27. 36. 72.] 1456
1626
[27. 36. 74.] 1626
1714
[27. 40. 42.] 1714
1703
[27. 40. 44.] 1703
1735
[27. 40. 46.] 1735
2097
[27. 40. 48.] 2097
1367
[27. 40. 50.] 1367
2168
[27. 40. 52.] 2168
1544
[27. 40. 54.] 1544
2057
[27. 40. 56.] 2057
2178
[27. 40. 58.] 2178
2145
[27. 40. 60.] 2145
2073
[27. 40. 62.] 2073
1642
[27. 40. 64.] 1642
2048
[27. 40. 66.] 2048
1312
[27. 40. 68.] 1312
1487
[27. 40. 72.] 1487
1643
[27. 40. 74.] 1643
1375
[27. 42. 44.] 1375
1431
[27. 42. 46.] 1431
1678
[27. 42. 48.] 1678
1053
1725
[27. 42. 52.] 1725
1096
1639
[

1967
[29. 60. 70.] 1967
2345
[29. 60. 72.] 2345
2347
[29. 60. 74.] 2347
2509
[29. 62. 64.] 2509
2884
[29. 62. 66.] 2884
1916
[29. 62. 68.] 1916
1959
[29. 62. 70.] 1959
2246
[29. 62. 72.] 2246
2326
[29. 62. 74.] 2326
2489
[29. 64. 66.] 2489
1633
[29. 64. 68.] 1633
1718
[29. 64. 70.] 1718
2133
[29. 64. 72.] 2133
1827
[29. 64. 74.] 1827
1828
[29. 66. 68.] 1828
1878
[29. 66. 70.] 1878
2345
[29. 66. 72.] 2345
2224
[29. 66. 74.] 2224
1303
[29. 68. 70.] 1303
1461
[29. 68. 72.] 1461
1578
[29. 68. 74.] 1578
1483
[29. 70. 72.] 1483
1561
[29. 70. 74.] 1561
1556
[29. 72. 74.] 1556
2310
[31. 34. 36.] 2310
1684
[31. 34. 38.] 1684
2385
[31. 34. 40.] 2385
2156
[31. 34. 42.] 2156
1961
[31. 34. 44.] 1961
1915
[31. 34. 46.] 1915
2228
[31. 34. 48.] 2228
1502
[31. 34. 50.] 1502
2386
[31. 34. 52.] 2386
1466
[31. 34. 54.] 1466
2258
[31. 34. 56.] 2258
2395
[31. 34. 58.] 2395
2379
[31. 34. 60.] 2379
2287
[31. 34. 62.] 2287
2105
[31. 34. 64.] 2105
2304
[31. 34. 66.] 2304
1429
[31. 34. 68.] 1429
1575
[31. 34. 70

2877
[34. 52. 66.] 2877
1936
[34. 52. 68.] 1936
1963
[34. 52. 70.] 1963
2265
[34. 52. 72.] 2265
2281
[34. 52. 74.] 2281
2034
[34. 54. 56.] 2034
2110
[34. 54. 58.] 2110
2066
[34. 54. 60.] 2066
2033
[34. 54. 62.] 2033
1602
[34. 54. 64.] 1602
1957
[34. 54. 66.] 1957
1435
[34. 54. 68.] 1435
1373
[34. 54. 70.] 1373
1336
[34. 54. 72.] 1336
1864
[34. 54. 74.] 1864
2883
[34. 56. 58.] 2883
2839
[34. 56. 60.] 2839
2791
[34. 56. 62.] 2791
2404
[34. 56. 64.] 2404
2730
[34. 56. 66.] 2730
1927
[34. 56. 68.] 1927
1891
[34. 56. 70.] 1891
2129
[34. 56. 72.] 2129
2236
[34. 56. 74.] 2236
2994
[34. 58. 60.] 2994
2913
[34. 58. 62.] 2913
2530
[34. 58. 64.] 2530
2885
[34. 58. 66.] 2885
1938
[34. 58. 68.] 1938
1968
[34. 58. 70.] 1968
2265
[34. 58. 72.] 2265
2289
[34. 58. 74.] 2289
2869
[34. 60. 62.] 2869
2486
[34. 60. 64.] 2486
2886
[34. 60. 66.] 2886
1894
[34. 60. 68.] 1894
1929
[34. 60. 70.] 1929
2265
[34. 60. 72.] 2265
2245
[34. 60. 74.] 2245
2428
[34. 62. 64.] 2428
2766
[34. 62. 66.] 2766
1886
[34. 62. 68

1379
[38. 60. 68.] 1379
1769
[38. 60. 70.] 1769
1641
[38. 60. 72.] 1641
1673
[38. 60. 74.] 1673
1861
[38. 62. 64.] 1861
2028
[38. 62. 66.] 2028
1384
[38. 62. 68.] 1384
1756
[38. 62. 70.] 1756
1609
[38. 62. 72.] 1609
1675
[38. 62. 74.] 1675
1792
[38. 64. 66.] 1792
1237
1555
[38. 64. 70.] 1555
1527
[38. 64. 72.] 1527
1413
[38. 64. 74.] 1413
1309
[38. 66. 68.] 1309
1692
[38. 66. 70.] 1692
1641
[38. 66. 72.] 1641
1585
[38. 66. 74.] 1585
1160
1064
1143
1338
[38. 70. 72.] 1338
1413
[38. 70. 74.] 1413
1155
2233
[40. 42. 44.] 2233
2204
[40. 42. 46.] 2204
2547
[40. 42. 48.] 2547
1655
[40. 42. 50.] 1655
2691
[40. 42. 52.] 2691
1717
[40. 42. 54.] 1717
2554
[40. 42. 56.] 2554
2696
[40. 42. 58.] 2696
2671
[40. 42. 60.] 2671
2588
[40. 42. 62.] 2588
2464
[40. 42. 64.] 2464
2596
[40. 42. 66.] 2596
1667
[40. 42. 68.] 1667
1741
[40. 42. 70.] 1741
2187
[40. 42. 72.] 2187
1908
[40. 42. 74.] 1908
2090
[40. 44. 46.] 2090
2413
[40. 44. 48.] 2413
1592
[40. 44. 50.] 1592
2575
[40. 44. 52.] 2575
1854
[40. 44. 5

2454
[44. 60. 66.] 2454
1657
[44. 60. 68.] 1657
1625
[44. 60. 70.] 1625
1874
[44. 60. 72.] 1874
1979
[44. 60. 74.] 1979
2140
[44. 62. 64.] 2140
2371
[44. 62. 66.] 2371
1655
[44. 62. 68.] 1655
1621
[44. 62. 70.] 1621
1811
[44. 62. 72.] 1811
1977
[44. 62. 74.] 1977
2085
[44. 64. 66.] 2085
1445
[44. 64. 68.] 1445
1447
[44. 64. 70.] 1447
1725
[44. 64. 72.] 1725
1625
[44. 64. 74.] 1625
1565
[44. 66. 68.] 1565
1538
[44. 66. 70.] 1538
1874
[44. 66. 72.] 1874
1868
[44. 66. 74.] 1868
1125
1221
1390
[44. 68. 74.] 1390
1193
1330
[44. 70. 74.] 1330
1288
[44. 72. 74.] 1288
1411
[46. 48. 50.] 1411
2393
[46. 48. 52.] 2393
1671
[46. 48. 54.] 1671
2253
[46. 48. 56.] 2253
2403
[46. 48. 58.] 2403
2385
[46. 48. 60.] 2385
2297
[46. 48. 62.] 2297
2014
[46. 48. 64.] 2014
2304
[46. 48. 66.] 2304
1441
[46. 48. 68.] 1441
1374
[46. 48. 70.] 1374
1797
[46. 48. 72.] 1797
1781
[46. 48. 74.] 1781
1528
[46. 50. 52.] 1528
1091
1453
[46. 50. 56.] 1453
1533
[46. 50. 58.] 1533
1507
[46. 50. 60.] 1507
1497
[46. 50. 62.] 1

1799
[56. 66. 70.] 1799
2201
[56. 66. 72.] 2201
2165
[56. 66. 74.] 2165
1291
[56. 68. 70.] 1291
1453
[56. 68. 72.] 1453
1589
[56. 68. 74.] 1589
1421
[56. 70. 72.] 1421
1544
[56. 70. 74.] 1544
1520
[56. 72. 74.] 1520
3014
[58. 60. 62.] 3014
2583
[58. 60. 64.] 2583
3020
[58. 60. 66.] 3020
1936
[58. 60. 68.] 1936
1966
[58. 60. 70.] 1966
2345
[58. 60. 72.] 2345
2359
[58. 60. 74.] 2359
2524
[58. 62. 64.] 2524
2892
[58. 62. 66.] 2892
1931
[58. 62. 68.] 1931
1959
[58. 62. 70.] 1959
2246
[58. 62. 72.] 2246
2341
[58. 62. 74.] 2341
2496
[58. 64. 66.] 2496
1647
[58. 64. 68.] 1647
1717
[58. 64. 70.] 1717
2133
[58. 64. 72.] 2133
1841
[58. 64. 74.] 1841
1835
[58. 66. 68.] 1835
1877
[58. 66. 70.] 1877
2345
[58. 66. 72.] 2345
2231
[58. 66. 74.] 2231
1302
[58. 68. 70.] 1302
1461
[58. 68. 72.] 1461
1592
[58. 68. 74.] 1592
1483
[58. 70. 72.] 1483
1560
[58. 70. 74.] 1560
1556
[58. 72. 74.] 1556
2478
[60. 62. 64.] 2478
2892
[60. 62. 66.] 2892
1885
[60. 62. 68.] 1885
1919
[60. 62. 70.] 1919
2246
[60. 62. 72

1351
[1. 3. 5. 7.] 1351
1249
1197
1203
1376
[ 1.  3.  5. 29.] 1376
1376
[ 1.  3.  5. 34.] 1376
1325
[ 1.  3.  5. 36.] 1325
1360
[ 1.  3.  5. 40.] 1360
1318
[ 1.  3.  5. 48.] 1318
1376
[ 1.  3.  5. 52.] 1376
1347
[ 1.  3.  5. 56.] 1347
1376
[ 1.  3.  5. 58.] 1376
1376
[ 1.  3.  5. 60.] 1376
1327
[ 1.  3.  5. 62.] 1327
1368
[ 1.  3.  5. 66.] 1368
1309
[1. 3. 7. 9.] 1309
1276
1277
1454
[ 1.  3.  7. 29.] 1454
1427
[ 1.  3.  7. 34.] 1427
1403
[ 1.  3.  7. 36.] 1403
1436
[ 1.  3.  7. 40.] 1436
1396
[ 1.  3.  7. 48.] 1396
1454
[ 1.  3.  7. 52.] 1454
1418
[ 1.  3.  7. 56.] 1418
1454
[ 1.  3.  7. 58.] 1454
1454
[ 1.  3.  7. 60.] 1454
1386
[ 1.  3.  7. 62.] 1386
1436
[ 1.  3.  7. 66.] 1436
1189
1160
1337
[ 1.  3.  9. 29.] 1337
1315
[ 1.  3.  9. 34.] 1315
1286
[ 1.  3.  9. 36.] 1286
1321
[ 1.  3.  9. 40.] 1321
1279
[ 1.  3.  9. 48.] 1279
1337
[ 1.  3.  9. 52.] 1337
1307
[ 1.  3.  9. 56.] 1307
1337
[ 1.  3.  9. 58.] 1337
1337
[ 1.  3.  9. 60.] 1337
1274
1322
[ 1.  3.  9. 66.] 1322
1129
1303
[ 1.  

1544
[ 1.  7. 34. 48.] 1544
1605
[ 1.  7. 34. 52.] 1605
1569
[ 1.  7. 34. 56.] 1569
1607
[ 1.  7. 34. 58.] 1607
1607
[ 1.  7. 34. 60.] 1607
1531
[ 1.  7. 34. 62.] 1531
1593
[ 1.  7. 34. 66.] 1593
1275
1282
[ 1.  7. 34. 72.] 1282
1562
[ 1.  7. 36. 40.] 1562
1333
[ 1.  7. 36. 42.] 1333
1558
[ 1.  7. 36. 48.] 1558
1578
[ 1.  7. 36. 52.] 1578
1538
[ 1.  7. 36. 56.] 1538
1580
[ 1.  7. 36. 58.] 1580
1580
[ 1.  7. 36. 60.] 1580
1496
[ 1.  7. 36. 62.] 1496
1561
[ 1.  7. 36. 66.] 1561
1241
1243
1371
[ 1.  7. 40. 42.] 1371
1553
[ 1.  7. 40. 48.] 1553
1614
[ 1.  7. 40. 52.] 1614
1574
[ 1.  7. 40. 56.] 1574
1616
[ 1.  7. 40. 58.] 1616
1616
[ 1.  7. 40. 60.] 1616
1538
[ 1.  7. 40. 62.] 1538
1597
[ 1.  7. 40. 66.] 1597
1272
1285
[ 1.  7. 40. 72.] 1285
1328
[ 1.  7. 42. 48.] 1328
1380
[ 1.  7. 42. 52.] 1380
1350
[ 1.  7. 42. 56.] 1350
1381
[ 1.  7. 42. 58.] 1381
1381
[ 1.  7. 42. 60.] 1381
1313
[ 1.  7. 42. 62.] 1313
1376
[ 1.  7. 42. 66.] 1376
1100
1178
1569
[ 1.  7. 48. 52.] 1569
1529
[ 1.  7. 48. 

1441
[ 1. 25. 36. 48.] 1441
1452
[ 1. 25. 36. 52.] 1452
1415
[ 1. 25. 36. 56.] 1415
1454
[ 1. 25. 36. 58.] 1454
1454
[ 1. 25. 36. 60.] 1454
1380
[ 1. 25. 36. 62.] 1380
1436
[ 1. 25. 36. 66.] 1436
1430
[ 1. 25. 40. 48.] 1430
1466
[ 1. 25. 40. 52.] 1466
1429
[ 1. 25. 40. 56.] 1429
1468
[ 1. 25. 40. 58.] 1468
1468
[ 1. 25. 40. 60.] 1468
1400
[ 1. 25. 40. 62.] 1400
1450
[ 1. 25. 40. 66.] 1450
1446
[ 1. 25. 48. 52.] 1446
1409
[ 1. 25. 48. 56.] 1409
1448
[ 1. 25. 48. 58.] 1448
1448
[ 1. 25. 48. 60.] 1448
1374
[ 1. 25. 48. 62.] 1374
1430
[ 1. 25. 48. 66.] 1430
1446
[ 1. 25. 52. 56.] 1446
1484
[ 1. 25. 52. 58.] 1484
1484
[ 1. 25. 52. 60.] 1484
1410
[ 1. 25. 52. 62.] 1410
1466
[ 1. 25. 52. 66.] 1466
1447
[ 1. 25. 56. 58.] 1447
1447
[ 1. 25. 56. 60.] 1447
1386
[ 1. 25. 56. 62.] 1386
1429
[ 1. 25. 56. 66.] 1429
1486
[ 1. 25. 58. 60.] 1486
1412
[ 1. 25. 58. 62.] 1412
1468
[ 1. 25. 58. 66.] 1468
1412
[ 1. 25. 60. 62.] 1412
1468
[ 1. 25. 60. 66.] 1468
1394
[ 1. 25. 62. 66.] 1394
1588
[ 1. 29. 34. 36

1624
[ 1. 52. 56. 58.] 1624
1624
[ 1. 52. 56. 60.] 1624
1554
[ 1. 52. 56. 62.] 1554
1268
1604
[ 1. 52. 56. 66.] 1604
1306
[ 1. 52. 56. 68.] 1306
1295
[ 1. 52. 56. 72.] 1295
1667
[ 1. 52. 58. 60.] 1667
1583
[ 1. 52. 58. 62.] 1583
1297
[ 1. 52. 58. 64.] 1297
1647
[ 1. 52. 58. 66.] 1647
1317
[ 1. 52. 58. 68.] 1317
1328
[ 1. 52. 58. 72.] 1328
1583
[ 1. 52. 60. 62.] 1583
1297
[ 1. 52. 60. 64.] 1297
1647
[ 1. 52. 60. 66.] 1647
1317
[ 1. 52. 60. 68.] 1317
1328
[ 1. 52. 60. 72.] 1328
1235
1563
[ 1. 52. 62. 66.] 1563
1275
1266
1288
[ 1. 52. 64. 66.] 1288
1045
1148
1305
[ 1. 52. 66. 68.] 1305
1328
[ 1. 52. 66. 72.] 1328
1062
1625
[ 1. 56. 58. 60.] 1625
1555
[ 1. 56. 58. 62.] 1555
1605
[ 1. 56. 58. 66.] 1605
1307
[ 1. 56. 58. 68.] 1307
1295
[ 1. 56. 58. 72.] 1295
1555
[ 1. 56. 60. 62.] 1555
1605
[ 1. 56. 60. 66.] 1605
1307
[ 1. 56. 60. 68.] 1307
1295
[ 1. 56. 60. 72.] 1295
1535
[ 1. 56. 62. 66.] 1535
1265
1240
1295
[ 1. 56. 66. 68.] 1295
1295
[ 1. 56. 66. 72.] 1295
1054
1585
[ 1. 58. 60. 62.] 158

1460
[ 2. 29. 36. 52.] 1460
1338
[ 2. 29. 36. 56.] 1338
1468
[ 2. 29. 36. 58.] 1468
1424
[ 2. 29. 36. 60.] 1424
1417
[ 2. 29. 36. 62.] 1417
1277
1321
[ 2. 29. 36. 66.] 1321
1282
[ 2. 29. 40. 42.] 1282
1504
[ 2. 29. 40. 44.] 1504
1384
[ 2. 29. 40. 48.] 1384
1495
[ 2. 29. 40. 52.] 1495
1374
[ 2. 29. 40. 56.] 1374
1503
[ 2. 29. 40. 58.] 1503
1460
[ 2. 29. 40. 60.] 1460
1457
[ 2. 29. 40. 62.] 1457
1318
[ 2. 29. 40. 64.] 1318
1358
[ 2. 29. 40. 66.] 1358
1289
[ 2. 29. 42. 44.] 1289
1192
1284
[ 2. 29. 42. 52.] 1284
1177
1288
[ 2. 29. 42. 58.] 1288
1265
1241
1205
1196
1392
[ 2. 29. 44. 48.] 1392
1503
[ 2. 29. 44. 52.] 1503
1381
[ 2. 29. 44. 56.] 1381
1511
[ 2. 29. 44. 58.] 1511
1467
[ 2. 29. 44. 60.] 1467
1460
[ 2. 29. 44. 62.] 1460
1319
[ 2. 29. 44. 64.] 1319
1364
[ 2. 29. 44. 66.] 1364
1383
[ 2. 29. 48. 52.] 1383
1261
1391
[ 2. 29. 48. 58.] 1391
1367
[ 2. 29. 48. 60.] 1367
1340
[ 2. 29. 48. 62.] 1340
1212
1279
[ 2. 29. 48. 66.] 1279
1377
[ 2. 29. 52. 56.] 1377
1502
[ 2. 29. 52. 58.] 1502
145

1562
[ 3.  5. 11. 48.] 1562
1072
1720
[ 3.  5. 11. 52.] 1720
1226
1672
[ 3.  5. 11. 56.] 1672
1729
[ 3.  5. 11. 58.] 1729
1699
[ 3.  5. 11. 60.] 1699
1661
[ 3.  5. 11. 62.] 1661
1392
[ 3.  5. 11. 64.] 1392
1636
[ 3.  5. 11. 66.] 1636
1049
1235
1268
1312
[ 3.  5. 11. 74.] 1312
932
1106
863
959
856
1190
940
1393
[ 3.  5. 13. 29.] 1393
1137
1377
[ 3.  5. 13. 34.] 1377
1317
[ 3.  5. 13. 36.] 1317
991
1385
[ 3.  5. 13. 40.] 1385
1184
1112
1084
1264
869
1387
[ 3.  5. 13. 52.] 1387
943
1311
[ 3.  5. 13. 56.] 1311
1393
[ 3.  5. 13. 58.] 1393
1359
[ 3.  5. 13. 60.] 1359
1320
[ 3.  5. 13. 62.] 1320
1165
1284
[ 3.  5. 13. 66.] 1284
856
1011
1001
1025
1576
[ 3.  5. 15. 17.] 1576
1232
1197
1077
1411
[ 3.  5. 15. 25.] 1411
1114
1657
[ 3.  5. 15. 29.] 1657
1399
[ 3.  5. 15. 31.] 1399
1621
[ 3.  5. 15. 34.] 1621
1574
[ 3.  5. 15. 36.] 1574
1143
1636
[ 3.  5. 15. 40.] 1636
1433
[ 3.  5. 15. 42.] 1433
1216
1313
[ 3.  5. 15. 46.] 1313
1538
[ 3.  5. 15. 48.] 1538
1023
1648
[ 3.  5. 15. 52.] 1648
1053
1551

2223
[ 3.  5. 42. 66.] 2223
1373
[ 3.  5. 42. 68.] 1373
1551
[ 3.  5. 42. 70.] 1551
1927
[ 3.  5. 42. 72.] 1927
1551
[ 3.  5. 42. 74.] 1551
1693
[ 3.  5. 44. 46.] 1693
1985
[ 3.  5. 44. 48.] 1985
1349
[ 3.  5. 44. 50.] 1349
2133
[ 3.  5. 44. 52.] 2133
1449
[ 3.  5. 44. 54.] 1449
2037
[ 3.  5. 44. 56.] 2037
2142
[ 3.  5. 44. 58.] 2142
2108
[ 3.  5. 44. 60.] 2108
2077
[ 3.  5. 44. 62.] 2077
1852
[ 3.  5. 44. 64.] 1852
2041
[ 3.  5. 44. 66.] 2041
1355
[ 3.  5. 44. 68.] 1355
1454
[ 3.  5. 44. 70.] 1454
1625
[ 3.  5. 44. 72.] 1625
1587
[ 3.  5. 44. 74.] 1587
1969
[ 3.  5. 46. 48.] 1969
1310
[ 3.  5. 46. 50.] 1310
2096
[ 3.  5. 46. 52.] 2096
1397
[ 3.  5. 46. 54.] 1397
1994
[ 3.  5. 46. 56.] 1994
2105
[ 3.  5. 46. 58.] 2105
2076
[ 3.  5. 46. 60.] 2076
2021
[ 3.  5. 46. 62.] 2021
1819
[ 3.  5. 46. 64.] 1819
2024
[ 3.  5. 46. 66.] 2024
1253
1315
[ 3.  5. 46. 70.] 1315
1641
[ 3.  5. 46. 72.] 1641
1516
[ 3.  5. 46. 74.] 1516
1533
[ 3.  5. 48. 50.] 1533
2463
[ 3.  5. 48. 52.] 2463
1598
[ 3.  5. 4

1676
[ 3.  7. 23. 60.] 1676
1619
[ 3.  7. 23. 62.] 1619
1673
[ 3.  7. 23. 64.] 1673
1575
[ 3.  7. 23. 66.] 1575
972
1108
1575
[ 3.  7. 23. 72.] 1575
955
1697
[ 3.  7. 25. 27.] 1697
2447
[ 3.  7. 25. 29.] 2447
2001
[ 3.  7. 25. 31.] 2001
2319
[ 3.  7. 25. 34.] 2319
2385
[ 3.  7. 25. 36.] 2385
1640
[ 3.  7. 25. 38.] 1640
2421
[ 3.  7. 25. 40.] 2421
2053
[ 3.  7. 25. 42.] 2053
1956
[ 3.  7. 25. 44.] 1956
1936
[ 3.  7. 25. 46.] 1936
2346
[ 3.  7. 25. 48.] 2346
1565
[ 3.  7. 25. 50.] 1565
2439
[ 3.  7. 25. 52.] 2439
1625
[ 3.  7. 25. 54.] 1625
2323
[ 3.  7. 25. 56.] 2323
2447
[ 3.  7. 25. 58.] 2447
2421
[ 3.  7. 25. 60.] 2421
2345
[ 3.  7. 25. 62.] 2345
1988
[ 3.  7. 25. 64.] 1988
2329
[ 3.  7. 25. 66.] 2329
1461
[ 3.  7. 25. 68.] 1461
1571
[ 3.  7. 25. 70.] 1571
1853
[ 3.  7. 25. 72.] 1853
1786
[ 3.  7. 25. 74.] 1786
1911
[ 3.  7. 27. 29.] 1911
1484
[ 3.  7. 27. 31.] 1484
1793
[ 3.  7. 27. 34.] 1793
1869
[ 3.  7. 27. 36.] 1869
1044
1885
[ 3.  7. 27. 40.] 1885
1493
[ 3.  7. 27. 42.] 1493
14

1010
1402
[ 3.  9. 11. 15.] 1402
1565
[ 3.  9. 11. 17.] 1565
1223
1200
1036
1476
[ 3.  9. 11. 25.] 1476
1292
[ 3.  9. 11. 27.] 1292
1787
[ 3.  9. 11. 29.] 1787
1452
[ 3.  9. 11. 31.] 1452
1699
[ 3.  9. 11. 34.] 1699
1694
[ 3.  9. 11. 36.] 1694
1224
1765
[ 3.  9. 11. 40.] 1765
1472
[ 3.  9. 11. 42.] 1472
1391
[ 3.  9. 11. 44.] 1391
1397
[ 3.  9. 11. 46.] 1397
1620
[ 3.  9. 11. 48.] 1620
1127
1781
[ 3.  9. 11. 52.] 1781
1252
1738
[ 3.  9. 11. 56.] 1738
1787
[ 3.  9. 11. 58.] 1787
1765
[ 3.  9. 11. 60.] 1765
1707
[ 3.  9. 11. 62.] 1707
1412
[ 3.  9. 11. 64.] 1412
1684
[ 3.  9. 11. 66.] 1684
1062
1258
1296
[ 3.  9. 11. 72.] 1296
1346
[ 3.  9. 11. 74.] 1346
1022
1196
921
995
893
1244
1019
1457
[ 3.  9. 13. 29.] 1457
1186
1401
[ 3.  9. 13. 34.] 1401
1381
[ 3.  9. 13. 36.] 1381
982
1447
[ 3.  9. 13. 40.] 1447
1215
1141
1118
1328
[ 3.  9. 13. 48.] 1328
916
1451
[ 3.  9. 13. 52.] 1451
985
1370
[ 3.  9. 13. 56.] 1370
1457
[ 3.  9. 13. 58.] 1457
1431
[ 3.  9. 13. 60.] 1431
1369
[ 3.  9. 13. 62.] 

1777
[ 3.  9. 42. 44.] 1777
1759
[ 3.  9. 42. 46.] 1759
2053
[ 3.  9. 42. 48.] 2053
1384
[ 3.  9. 42. 50.] 1384
2183
[ 3.  9. 42. 52.] 2183
1320
[ 3.  9. 42. 54.] 1320
2101
[ 3.  9. 42. 56.] 2101
2187
[ 3.  9. 42. 58.] 2187
2177
[ 3.  9. 42. 60.] 2177
2097
[ 3.  9. 42. 62.] 2097
2005
[ 3.  9. 42. 64.] 2005
2124
[ 3.  9. 42. 66.] 2124
1303
[ 3.  9. 42. 68.] 1303
1520
[ 3.  9. 42. 70.] 1520
1829
[ 3.  9. 42. 72.] 1829
1499
[ 3.  9. 42. 74.] 1499
1630
[ 3.  9. 44. 46.] 1630
1902
[ 3.  9. 44. 48.] 1902
1321
[ 3.  9. 44. 50.] 1321
2053
[ 3.  9. 44. 52.] 2053
1414
[ 3.  9. 44. 54.] 1414
1983
[ 3.  9. 44. 56.] 1983
2059
[ 3.  9. 44. 58.] 2059
2033
[ 3.  9. 44. 60.] 2033
1997
[ 3.  9. 44. 62.] 1997
1751
[ 3.  9. 44. 64.] 1751
1949
[ 3.  9. 44. 66.] 1949
1300
[ 3.  9. 44. 68.] 1300
1434
[ 3.  9. 44. 70.] 1434
1528
[ 3.  9. 44. 72.] 1528
1549
[ 3.  9. 44. 74.] 1549
1879
[ 3.  9. 46. 48.] 1879
1273
2009
[ 3.  9. 46. 52.] 2009
1354
[ 3.  9. 46. 54.] 1354
1934
[ 3.  9. 46. 56.] 1934
2015
[ 3.  9. 4

1460
[ 3. 11. 44. 60.] 1460
1438
[ 3. 11. 44. 62.] 1438
1187
1387
[ 3. 11. 44. 66.] 1387
1034
1049
1167
1370
[ 3. 11. 46. 48.] 1370
1497
[ 3. 11. 46. 52.] 1497
1075
1458
[ 3. 11. 46. 56.] 1458
1506
[ 3. 11. 46. 58.] 1506
1479
[ 3. 11. 46. 60.] 1479
1441
[ 3. 11. 46. 62.] 1441
1203
1411
[ 3. 11. 46. 66.] 1411
972
1098
1140
1733
[ 3. 11. 48. 52.] 1733
1204
1680
[ 3. 11. 48. 56.] 1680
1742
[ 3. 11. 48. 58.] 1742
1724
[ 3. 11. 48. 60.] 1724
1658
[ 3. 11. 48. 62.] 1658
1361
[ 3. 11. 48. 64.] 1361
1653
[ 3. 11. 48. 66.] 1653
1145
1284
[ 3. 11. 48. 72.] 1284
1283
[ 3. 11. 48. 74.] 1283
1331
[ 3. 11. 52. 54.] 1331
1843
[ 3. 11. 52. 56.] 1843
1900
[ 3. 11. 52. 58.] 1900
1870
[ 3. 11. 52. 60.] 1870
1816
[ 3. 11. 52. 62.] 1816
1499
[ 3. 11. 52. 64.] 1499
1784
[ 3. 11. 52. 66.] 1784
1294
[ 3. 11. 52. 70.] 1294
1392
[ 3. 11. 52. 72.] 1392
1431
[ 3. 11. 52. 74.] 1431
1306
[ 3. 11. 54. 56.] 1306
1340
[ 3. 11. 54. 58.] 1340
1310
[ 3. 11. 54. 60.] 1310
1292
[ 3. 11. 54. 62.] 1292
931
1224
921
823
1172


1292
[ 3. 15. 40. 74.] 1292
1156
1270
1452
[ 3. 15. 42. 48.] 1452
1557
[ 3. 15. 42. 52.] 1557
1469
[ 3. 15. 42. 56.] 1469
1562
[ 3. 15. 42. 58.] 1562
1562
[ 3. 15. 42. 60.] 1562
1471
[ 3. 15. 42. 62.] 1471
1379
[ 3. 15. 42. 64.] 1379
1526
[ 3. 15. 42. 66.] 1526
1352
[ 3. 15. 42. 72.] 1352
1023
1083
1232
1333
[ 3. 15. 44. 52.] 1333
1257
1342
[ 3. 15. 44. 58.] 1342
1331
[ 3. 15. 44. 60.] 1331
1282
[ 3. 15. 44. 62.] 1282
1066
1272
1033
989
1363
[ 3. 15. 46. 48.] 1363
1450
[ 3. 15. 46. 52.] 1450
1364
[ 3. 15. 46. 56.] 1364
1459
[ 3. 15. 46. 58.] 1459
1448
[ 3. 15. 46. 60.] 1448
1376
[ 3. 15. 46. 62.] 1376
1165
1403
[ 3. 15. 46. 66.] 1403
1159
1029
1729
[ 3. 15. 48. 52.] 1729
1625
[ 3. 15. 48. 56.] 1625
1738
[ 3. 15. 48. 58.] 1738
1727
[ 3. 15. 48. 60.] 1727
1633
[ 3. 15. 48. 62.] 1633
1338
[ 3. 15. 48. 64.] 1338
1656
[ 3. 15. 48. 66.] 1656
1346
[ 3. 15. 48. 72.] 1346
1209
1740
[ 3. 15. 52. 56.] 1740
1848
[ 3. 15. 52. 58.] 1848
1837
[ 3. 15. 52. 60.] 1837
1743
[ 3. 15. 52. 62.] 1743
1434
[ 

1291
[ 3. 17. 46. 74.] 1291
1273
2118
[ 3. 17. 48. 52.] 2118
1372
[ 3. 17. 48. 54.] 1372
2011
[ 3. 17. 48. 56.] 2011
2127
[ 3. 17. 48. 58.] 2127
2109
[ 3. 17. 48. 60.] 2109
2016
[ 3. 17. 48. 62.] 2016
1687
[ 3. 17. 48. 64.] 1687
2025
[ 3. 17. 48. 66.] 2025
1262
1378
[ 3. 17. 48. 70.] 1378
1620
[ 3. 17. 48. 72.] 1620
1512
[ 3. 17. 48. 74.] 1512
1388
[ 3. 17. 50. 52.] 1388
923
1315
[ 3. 17. 50. 56.] 1315
1392
[ 3. 17. 50. 58.] 1392
1371
[ 3. 17. 50. 60.] 1371
1340
[ 3. 17. 50. 62.] 1340
1121
1323
[ 3. 17. 50. 66.] 1323
828
969
1053
1009
1477
[ 3. 17. 52. 54.] 1477
2152
[ 3. 17. 52. 56.] 2152
2263
[ 3. 17. 52. 58.] 2263
2233
[ 3. 17. 52. 60.] 2233
2152
[ 3. 17. 52. 62.] 2152
1809
[ 3. 17. 52. 64.] 1809
2149
[ 3. 17. 52. 66.] 2149
1378
[ 3. 17. 52. 68.] 1378
1509
[ 3. 17. 52. 70.] 1509
1728
[ 3. 17. 52. 72.] 1728
1638
[ 3. 17. 52. 74.] 1638
1437
[ 3. 17. 54. 56.] 1437
1486
[ 3. 17. 54. 58.] 1486
1456
[ 3. 17. 54. 60.] 1456
1427
[ 3. 17. 54. 62.] 1427
1024
1372
[ 3. 17. 54. 66.] 1372
967
99

1757
[ 3. 21. 34. 56.] 1757
1855
[ 3. 21. 34. 58.] 1855
1825
[ 3. 21. 34. 60.] 1825
1755
[ 3. 21. 34. 62.] 1755
1494
[ 3. 21. 34. 64.] 1494
1770
[ 3. 21. 34. 66.] 1770
1386
[ 3. 21. 34. 72.] 1386
1348
[ 3. 21. 34. 74.] 1348
1878
[ 3. 21. 36. 40.] 1878
1597
[ 3. 21. 36. 42.] 1597
1560
[ 3. 21. 36. 44.] 1560
1351
[ 3. 21. 36. 46.] 1351
1827
[ 3. 21. 36. 48.] 1827
1896
[ 3. 21. 36. 52.] 1896
1789
[ 3. 21. 36. 56.] 1789
1904
[ 3. 21. 36. 58.] 1904
1874
[ 3. 21. 36. 60.] 1874
1795
[ 3. 21. 36. 62.] 1795
1514
[ 3. 21. 36. 64.] 1514
1811
[ 3. 21. 36. 66.] 1811
1393
[ 3. 21. 36. 72.] 1393
1373
[ 3. 21. 36. 74.] 1373
1625
[ 3. 21. 40. 42.] 1625
1584
[ 3. 21. 40. 44.] 1584
1363
[ 3. 21. 40. 46.] 1363
1816
[ 3. 21. 40. 48.] 1816
1920
[ 3. 21. 40. 52.] 1920
1814
[ 3. 21. 40. 56.] 1814
1928
[ 3. 21. 40. 58.] 1928
1899
[ 3. 21. 40. 60.] 1899
1830
[ 3. 21. 40. 62.] 1830
1547
[ 3. 21. 40. 64.] 1547
1837
[ 3. 21. 40. 66.] 1837
1429
[ 3. 21. 40. 72.] 1429
1393
[ 3. 21. 40. 74.] 1393
1374
[ 3. 21. 42. 44

1963
[ 3. 25. 31. 34.] 1963
2013
[ 3. 25. 31. 36.] 2013
1410
[ 3. 25. 31. 38.] 1410
2058
[ 3. 25. 31. 40.] 2058
1871
[ 3. 25. 31. 42.] 1871
1698
[ 3. 25. 31. 44.] 1698
1661
[ 3. 25. 31. 46.] 1661
1976
[ 3. 25. 31. 48.] 1976
1278
[ 3. 25. 31. 50.] 1278
2063
[ 3. 25. 31. 52.] 2063
1214
1947
[ 3. 25. 31. 56.] 1947
2071
[ 3. 25. 31. 58.] 2071
2063
[ 3. 25. 31. 60.] 2063
1975
[ 3. 25. 31. 62.] 1975
1815
[ 3. 25. 31. 64.] 1815
1999
[ 3. 25. 31. 66.] 1999
1169
1292
[ 3. 25. 31. 70.] 1292
1692
[ 3. 25. 31. 72.] 1692
1376
[ 3. 25. 31. 74.] 1376
2330
[ 3. 25. 34. 36.] 2330
1616
[ 3. 25. 34. 38.] 1616
2369
[ 3. 25. 34. 40.] 2369
2033
[ 3. 25. 34. 42.] 2033
1919
[ 3. 25. 34. 44.] 1919
1908
[ 3. 25. 34. 46.] 1908
2291
[ 3. 25. 34. 48.] 2291
1490
[ 3. 25. 34. 50.] 1490
2386
[ 3. 25. 34. 52.] 2386
1581
[ 3. 25. 34. 54.] 1581
2285
[ 3. 25. 34. 56.] 2285
2392
[ 3. 25. 34. 58.] 2392
2366
[ 3. 25. 34. 60.] 2366
2298
[ 3. 25. 34. 62.] 2298
1984
[ 3. 25. 34. 64.] 1984
2288
[ 3. 25. 34. 66.] 2288
1484
[ 3. 

1489
[ 3. 27. 44. 58.] 1489
1463
[ 3. 27. 44. 60.] 1463
1431
[ 3. 27. 44. 62.] 1431
1157
1402
[ 3. 27. 44. 66.] 1402
1024
1129
1484
[ 3. 27. 46. 48.] 1484
1534
[ 3. 27. 46. 52.] 1534
1048
1465
[ 3. 27. 46. 56.] 1465
1543
[ 3. 27. 46. 58.] 1543
1522
[ 3. 27. 46. 60.] 1522
1470
[ 3. 27. 46. 62.] 1470
1207
1471
[ 3. 27. 46. 66.] 1471
1109
1105
1873
[ 3. 27. 48. 52.] 1873
1257
1790
[ 3. 27. 48. 56.] 1790
1882
[ 3. 27. 48. 58.] 1882
1862
[ 3. 27. 48. 60.] 1862
1782
[ 3. 27. 48. 62.] 1782
1427
[ 3. 27. 48. 64.] 1427
1792
[ 3. 27. 48. 66.] 1792
1346
[ 3. 27. 48. 72.] 1346
1350
[ 3. 27. 48. 74.] 1350
1308
[ 3. 27. 52. 54.] 1308
1856
[ 3. 27. 52. 56.] 1856
1943
[ 3. 27. 52. 58.] 1943
1917
[ 3. 27. 52. 60.] 1917
1843
[ 3. 27. 52. 62.] 1843
1468
[ 3. 27. 52. 64.] 1468
1839
[ 3. 27. 52. 66.] 1839
1381
[ 3. 27. 52. 72.] 1381
1407
[ 3. 27. 52. 74.] 1407
1275
1317
[ 3. 27. 54. 58.] 1317
1291
[ 3. 27. 54. 60.] 1291
1264
834
1213
746
1155
1860
[ 3. 27. 56. 58.] 1860
1834
[ 3. 27. 56. 60.] 1834
1798
[ 3

2247
[ 3. 31. 34. 58.] 2247
2234
[ 3. 31. 34. 60.] 2234
2147
[ 3. 31. 34. 62.] 2147
1999
[ 3. 31. 34. 64.] 1999
2167
[ 3. 31. 34. 66.] 2167
1322
[ 3. 31. 34. 68.] 1322
1497
[ 3. 31. 34. 70.] 1497
1859
[ 3. 31. 34. 72.] 1859
1497
[ 3. 31. 34. 74.] 1497
1547
[ 3. 31. 36. 38.] 1547
2264
[ 3. 31. 36. 40.] 2264
2053
[ 3. 31. 36. 42.] 2053
1842
[ 3. 31. 36. 44.] 1842
1810
[ 3. 31. 36. 46.] 1810
2181
[ 3. 31. 36. 48.] 2181
1421
[ 3. 31. 36. 50.] 1421
2268
[ 3. 31. 36. 52.] 2268
1321
[ 3. 31. 36. 54.] 1321
2142
[ 3. 31. 36. 56.] 2142
2277
[ 3. 31. 36. 58.] 2277
2264
[ 3. 31. 36. 60.] 2264
2168
[ 3. 31. 36. 62.] 2168
2010
[ 3. 31. 36. 64.] 2010
2191
[ 3. 31. 36. 66.] 2191
1280
[ 3. 31. 36. 68.] 1280
1447
[ 3. 31. 36. 70.] 1447
1850
[ 3. 31. 36. 72.] 1850
1496
[ 3. 31. 36. 74.] 1496
1624
[ 3. 31. 38. 40.] 1624
1485
[ 3. 31. 38. 42.] 1485
1397
[ 3. 31. 38. 44.] 1397
1248
1477
[ 3. 31. 38. 48.] 1477
1090
1619
[ 3. 31. 38. 52.] 1619
965
1551
[ 3. 31. 38. 56.] 1551
1624
[ 3. 31. 38. 58.] 1624
1613
[

2577
[ 3. 34. 52. 66.] 2577
1674
[ 3. 34. 52. 68.] 1674
1803
[ 3. 34. 52. 70.] 1803
2097
[ 3. 34. 52. 72.] 2097
1949
[ 3. 34. 52. 74.] 1949
1738
[ 3. 34. 54. 56.] 1738
1777
[ 3. 34. 54. 58.] 1777
1743
[ 3. 34. 54. 60.] 1743
1720
[ 3. 34. 54. 62.] 1720
1342
[ 3. 34. 54. 64.] 1342
1655
[ 3. 34. 54. 66.] 1655
1171
1211
1168
1530
[ 3. 34. 54. 74.] 1530
2588
[ 3. 34. 56. 58.] 2588
2554
[ 3. 34. 56. 60.] 2554
2516
[ 3. 34. 56. 62.] 2516
2167
[ 3. 34. 56. 64.] 2167
2466
[ 3. 34. 56. 66.] 2466
1667
[ 3. 34. 56. 68.] 1667
1733
[ 3. 34. 56. 70.] 1733
1995
[ 3. 34. 56. 72.] 1995
1940
[ 3. 34. 56. 74.] 1940
2672
[ 3. 34. 58. 60.] 2672
2600
[ 3. 34. 58. 62.] 2600
2271
[ 3. 34. 58. 64.] 2271
2584
[ 3. 34. 58. 66.] 2584
1675
[ 3. 34. 58. 68.] 1675
1807
[ 3. 34. 58. 70.] 1807
2097
[ 3. 34. 58. 72.] 2097
1956
[ 3. 34. 58. 74.] 1956
2567
[ 3. 34. 60. 62.] 2567
2237
[ 3. 34. 60. 64.] 2237
2584
[ 3. 34. 60. 66.] 2584
1641
[ 3. 34. 60. 68.] 1641
1778
[ 3. 34. 60. 70.] 1778
2097
[ 3. 34. 60. 72.] 2097
1922


1421
[ 3. 38. 56. 74.] 1421
1894
[ 3. 38. 58. 60.] 1894
1890
[ 3. 38. 58. 62.] 1890
1681
[ 3. 38. 58. 64.] 1681
1827
[ 3. 38. 58. 66.] 1827
1641
[ 3. 38. 58. 70.] 1641
1502
[ 3. 38. 58. 72.] 1502
1433
[ 3. 38. 58. 74.] 1433
1865
[ 3. 38. 60. 62.] 1865
1656
[ 3. 38. 60. 64.] 1656
1827
[ 3. 38. 60. 66.] 1827
1618
[ 3. 38. 60. 70.] 1618
1502
[ 3. 38. 60. 72.] 1502
1408
[ 3. 38. 60. 74.] 1408
1654
[ 3. 38. 62. 64.] 1654
1799
[ 3. 38. 62. 66.] 1799
1612
[ 3. 38. 62. 70.] 1612
1477
[ 3. 38. 62. 72.] 1477
1415
[ 3. 38. 62. 74.] 1415
1603
[ 3. 38. 64. 66.] 1603
1438
[ 3. 38. 64. 70.] 1438
1412
[ 3. 38. 64. 72.] 1412
1195
1553
[ 3. 38. 66. 70.] 1553
1502
[ 3. 38. 66. 72.] 1502
1341
[ 3. 38. 66. 74.] 1341
1260
1252
1016
1942
[ 3. 40. 42. 44.] 1942
1946
[ 3. 40. 42. 46.] 1946
2260
[ 3. 40. 42. 48.] 2260
1503
[ 3. 40. 42. 50.] 1503
2389
[ 3. 40. 42. 52.] 2389
1414
[ 3. 40. 42. 54.] 1414
2283
[ 3. 40. 42. 56.] 2283
2394
[ 3. 40. 42. 58.] 2394
2381
[ 3. 40. 42. 60.] 2381
2303
[ 3. 40. 42. 62.] 2303


1932
[ 3. 44. 52. 64.] 1932
2140
[ 3. 44. 52. 66.] 2140
1432
[ 3. 44. 52. 68.] 1432
1502
[ 3. 44. 52. 70.] 1502
1710
[ 3. 44. 52. 72.] 1710
1673
[ 3. 44. 52. 74.] 1673
1495
[ 3. 44. 54. 56.] 1495
1536
[ 3. 44. 54. 58.] 1536
1502
[ 3. 44. 54. 60.] 1502
1495
[ 3. 44. 54. 62.] 1495
1201
1417
[ 3. 44. 54. 66.] 1417
1030
1040
978
1327
[ 3. 44. 54. 74.] 1327
2163
[ 3. 44. 56. 58.] 2163
2129
[ 3. 44. 56. 60.] 2129
2118
[ 3. 44. 56. 62.] 2118
1846
[ 3. 44. 56. 64.] 1846
2044
[ 3. 44. 56. 66.] 2044
1427
[ 3. 44. 56. 68.] 1427
1443
[ 3. 44. 56. 70.] 1443
1625
[ 3. 44. 56. 72.] 1625
1662
[ 3. 44. 56. 74.] 1662
2234
[ 3. 44. 58. 60.] 2234
2199
[ 3. 44. 58. 62.] 2199
1933
[ 3. 44. 58. 64.] 1933
2149
[ 3. 44. 58. 66.] 2149
1433
[ 3. 44. 58. 68.] 1433
1506
[ 3. 44. 58. 70.] 1506
1710
[ 3. 44. 58. 72.] 1710
1682
[ 3. 44. 58. 74.] 1682
2166
[ 3. 44. 60. 62.] 2166
1899
[ 3. 44. 60. 64.] 1899
2149
[ 3. 44. 60. 66.] 2149
1399
[ 3. 44. 60. 68.] 1399
1477
[ 3. 44. 60. 70.] 1477
1710
[ 3. 44. 60. 72.] 1710
1

1568
[ 3. 54. 62. 74.] 1568
1274
1116
1466
[ 3. 54. 66. 74.] 1466
2670
[ 3. 56. 58. 60.] 2670
2627
[ 3. 56. 58. 62.] 2627
2243
[ 3. 56. 58. 64.] 2243
2568
[ 3. 56. 58. 66.] 2568
1701
[ 3. 56. 58. 68.] 1701
1770
[ 3. 56. 58. 70.] 1770
2067
[ 3. 56. 58. 72.] 2067
2023
[ 3. 56. 58. 74.] 2023
2594
[ 3. 56. 60. 62.] 2594
2209
[ 3. 56. 60. 64.] 2209
2568
[ 3. 56. 60. 66.] 2568
1667
[ 3. 56. 60. 68.] 1667
1741
[ 3. 56. 60. 70.] 1741
2067
[ 3. 56. 60. 72.] 2067
1989
[ 3. 56. 60. 74.] 1989
2180
[ 3. 56. 62. 64.] 2180
2494
[ 3. 56. 62. 66.] 2494
1669
[ 3. 56. 62. 68.] 1669
1748
[ 3. 56. 62. 70.] 1748
2004
[ 3. 56. 62. 72.] 2004
1987
[ 3. 56. 62. 74.] 1987
2144
[ 3. 56. 64. 66.] 2144
1417
[ 3. 56. 64. 68.] 1417
1536
[ 3. 56. 64. 70.] 1536
1888
[ 3. 56. 64. 72.] 1888
1562
[ 3. 56. 64. 74.] 1562
1592
[ 3. 56. 66. 68.] 1592
1664
[ 3. 56. 66. 70.] 1664
2067
[ 3. 56. 66. 72.] 2067
1887
[ 3. 56. 66. 74.] 1887
1140
1319
[ 3. 56. 68. 72.] 1319
1318
[ 3. 56. 68. 74.] 1318
1343
[ 3. 56. 70. 72.] 1343
1386


978
1619
[ 5.  7. 23. 29.] 1619
1565
[ 5.  7. 23. 31.] 1565
1575
[ 5.  7. 23. 34.] 1575
1585
[ 5.  7. 23. 36.] 1585
1176
1619
[ 5.  7. 23. 40.] 1619
1569
[ 5.  7. 23. 42.] 1569
1286
[ 5.  7. 23. 44.] 1286
1297
[ 5.  7. 23. 46.] 1297
1528
[ 5.  7. 23. 48.] 1528
1034
1620
[ 5.  7. 23. 52.] 1620
748
1512
[ 5.  7. 23. 56.] 1512
1620
[ 5.  7. 23. 58.] 1620
1575
[ 5.  7. 23. 60.] 1575
1536
[ 5.  7. 23. 62.] 1536
1601
[ 5.  7. 23. 64.] 1601
1484
[ 5.  7. 23. 66.] 1484
940
1095
1484
[ 5.  7. 23. 72.] 1484
921
1715
[ 5.  7. 25. 27.] 1715
2538
[ 5.  7. 25. 29.] 2538
1998
[ 5.  7. 25. 31.] 1998
2465
[ 5.  7. 25. 34.] 2465
2474
[ 5.  7. 25. 36.] 2474
1829
[ 5.  7. 25. 38.] 1829
2519
[ 5.  7. 25. 40.] 2519
2177
[ 5.  7. 25. 42.] 2177
2108
[ 5.  7. 25. 44.] 2108
2031
[ 5.  7. 25. 46.] 2031
2429
[ 5.  7. 25. 48.] 2429
1608
[ 5.  7. 25. 50.] 1608
2530
[ 5.  7. 25. 52.] 2530
1780
[ 5.  7. 25. 54.] 1780
2402
[ 5.  7. 25. 56.] 2402
2539
[ 5.  7. 25. 58.] 2539
2512
[ 5.  7. 25. 60.] 2512
2441
[ 5.  7. 25.

2616
[ 5.  7. 62. 66.] 2616
1741
[ 5.  7. 62. 68.] 1741
1880
[ 5.  7. 62. 70.] 1880
2019
[ 5.  7. 62. 72.] 2019
2109
[ 5.  7. 62. 74.] 2109
2267
[ 5.  7. 64. 66.] 2267
1496
[ 5.  7. 64. 68.] 1496
1665
[ 5.  7. 64. 70.] 1665
1926
[ 5.  7. 64. 72.] 1926
1685
[ 5.  7. 64. 74.] 1685
1675
[ 5.  7. 66. 68.] 1675
1811
[ 5.  7. 66. 70.] 1811
2109
[ 5.  7. 66. 72.] 2109
2024
[ 5.  7. 66. 74.] 2024
1261
1324
[ 5.  7. 68. 72.] 1324
1448
[ 5.  7. 68. 74.] 1448
1433
[ 5.  7. 70. 72.] 1433
1503
[ 5.  7. 70. 74.] 1503
1410
[ 5.  7. 72. 74.] 1410
1018
1335
[ 5.  9. 11. 15.] 1335
1537
[ 5.  9. 11. 17.] 1537
1223
1257
962
1488
[ 5.  9. 11. 25.] 1488
1260
1794
[ 5.  9. 11. 29.] 1794
1416
[ 5.  9. 11. 31.] 1416
1751
[ 5.  9. 11. 34.] 1751
1701
[ 5.  9. 11. 36.] 1701
1346
[ 5.  9. 11. 38.] 1346
1781
[ 5.  9. 11. 40.] 1781
1505
[ 5.  9. 11. 42.] 1505
1446
[ 5.  9. 11. 44.] 1446
1435
[ 5.  9. 11. 46.] 1435
1615
[ 5.  9. 11. 48.] 1615
1092
1790
[ 5.  9. 11. 52.] 1790
1322
[ 5.  9. 11. 54.] 1322
1730
[ 5.  9. 

1977
[ 5.  9. 38. 58.] 1977
1945
[ 5.  9. 38. 60.] 1945
1935
[ 5.  9. 38. 62.] 1935
1712
[ 5.  9. 38. 64.] 1712
1871
[ 5.  9. 38. 66.] 1871
1272
1706
[ 5.  9. 38. 70.] 1706
1474
[ 5.  9. 38. 72.] 1474
1550
[ 5.  9. 38. 74.] 1550
2304
[ 5.  9. 40. 42.] 2304
2206
[ 5.  9. 40. 44.] 2206
2102
[ 5.  9. 40. 46.] 2102
2483
[ 5.  9. 40. 48.] 2483
1688
[ 5.  9. 40. 50.] 1688
2658
[ 5.  9. 40. 52.] 2658
1862
[ 5.  9. 40. 54.] 1862
2549
[ 5.  9. 40. 56.] 2549
2665
[ 5.  9. 40. 58.] 2665
2627
[ 5.  9. 40. 60.] 2627
2570
[ 5.  9. 40. 62.] 2570
2248
[ 5.  9. 40. 64.] 2248
2538
[ 5.  9. 40. 66.] 2538
1679
[ 5.  9. 40. 68.] 1679
1859
[ 5.  9. 40. 70.] 1859
1961
[ 5.  9. 40. 72.] 1961
2028
[ 5.  9. 40. 74.] 2028
1929
[ 5.  9. 42. 44.] 1929
1862
[ 5.  9. 42. 46.] 1862
2166
[ 5.  9. 42. 48.] 2166
1444
[ 5.  9. 42. 50.] 1444
2311
[ 5.  9. 42. 52.] 2311
1512
[ 5.  9. 42. 54.] 1512
2215
[ 5.  9. 42. 56.] 2215
2315
[ 5.  9. 42. 58.] 2315
2293
[ 5.  9. 42. 60.] 2293
2220
[ 5.  9. 42. 62.] 2220
2105
[ 5.  9. 4

1444
[ 5. 11. 36. 64.] 1444
1711
[ 5. 11. 36. 66.] 1711
1260
1271
1418
[ 5. 11. 36. 74.] 1418
1421
[ 5. 11. 38. 40.] 1421
1208
1208
1118
1252
1414
[ 5. 11. 38. 52.] 1414
1061
1375
[ 5. 11. 38. 56.] 1375
1420
[ 5. 11. 38. 58.] 1420
1388
[ 5. 11. 38. 60.] 1388
1381
[ 5. 11. 38. 62.] 1381
1174
1323
[ 5. 11. 38. 66.] 1323
1226
1015
1158
1586
[ 5. 11. 40. 42.] 1586
1531
[ 5. 11. 40. 44.] 1531
1535
[ 5. 11. 40. 46.] 1535
1720
[ 5. 11. 40. 48.] 1720
1892
[ 5. 11. 40. 52.] 1892
1400
[ 5. 11. 40. 54.] 1400
1817
[ 5. 11. 40. 56.] 1817
1902
[ 5. 11. 40. 58.] 1902
1864
[ 5. 11. 40. 60.] 1864
1826
[ 5. 11. 40. 62.] 1826
1523
[ 5. 11. 40. 64.] 1523
1788
[ 5. 11. 40. 66.] 1788
1352
[ 5. 11. 40. 70.] 1352
1353
[ 5. 11. 40. 72.] 1353
1486
[ 5. 11. 40. 74.] 1486
1289
[ 5. 11. 42. 44.] 1289
1312
[ 5. 11. 42. 46.] 1312
1450
[ 5. 11. 42. 48.] 1450
1594
[ 5. 11. 42. 52.] 1594
1097
1536
[ 5. 11. 42. 56.] 1536
1599
[ 5. 11. 42. 58.] 1599
1581
[ 5. 11. 42. 60.] 1581
1524
[ 5. 11. 42. 62.] 1524
1402
[ 5. 11. 42

1225
1515
[ 5. 15. 25. 34.] 1515
1487
[ 5. 15. 25. 36.] 1487
1532
[ 5. 15. 25. 40.] 1532
1331
[ 5. 15. 25. 42.] 1331
1167
1246
1459
[ 5. 15. 25. 48.] 1459
1543
[ 5. 15. 25. 52.] 1543
1441
[ 5. 15. 25. 56.] 1441
1552
[ 5. 15. 25. 58.] 1552
1542
[ 5. 15. 25. 60.] 1542
1463
[ 5. 15. 25. 62.] 1463
1176
1484
[ 5. 15. 25. 66.] 1484
1155
1158
1461
[ 5. 15. 29. 31.] 1461
1759
[ 5. 15. 29. 34.] 1759
1710
[ 5. 15. 29. 36.] 1710
1776
[ 5. 15. 29. 40.] 1776
1563
[ 5. 15. 29. 42.] 1563
1344
[ 5. 15. 29. 44.] 1344
1431
[ 5. 15. 29. 46.] 1431
1670
[ 5. 15. 29. 48.] 1670
1786
[ 5. 15. 29. 52.] 1786
1675
[ 5. 15. 29. 56.] 1675
1796
[ 5. 15. 29. 58.] 1796
1786
[ 5. 15. 29. 60.] 1786
1695
[ 5. 15. 29. 62.] 1695
1396
[ 5. 15. 29. 64.] 1396
1728
[ 5. 15. 29. 66.] 1728
1377
[ 5. 15. 29. 72.] 1377
1316
[ 5. 15. 29. 74.] 1316
1426
[ 5. 15. 31. 34.] 1426
1384
[ 5. 15. 31. 36.] 1384
1453
[ 5. 15. 31. 40.] 1453
1333
[ 5. 15. 31. 42.] 1333
1105
1170
1344
[ 5. 15. 31. 48.] 1344
1452
[ 5. 15. 31. 52.] 1452
1349
[ 5

2168
[ 5. 17. 36. 52.] 2168
1492
[ 5. 17. 36. 54.] 1492
2048
[ 5. 17. 36. 56.] 2048
2178
[ 5. 17. 36. 58.] 2178
2136
[ 5. 17. 36. 60.] 2136
2071
[ 5. 17. 36. 62.] 2071
1754
[ 5. 17. 36. 64.] 1754
2064
[ 5. 17. 36. 66.] 2064
1373
[ 5. 17. 36. 68.] 1373
1501
[ 5. 17. 36. 70.] 1501
1596
[ 5. 17. 36. 72.] 1596
1620
[ 5. 17. 36. 74.] 1620
1619
[ 5. 17. 38. 40.] 1619
1432
[ 5. 17. 38. 42.] 1432
1357
[ 5. 17. 38. 44.] 1357
1245
1469
[ 5. 17. 38. 48.] 1469
1010
1612
[ 5. 17. 38. 52.] 1612
1121
1546
[ 5. 17. 38. 56.] 1546
1618
[ 5. 17. 38. 58.] 1618
1585
[ 5. 17. 38. 60.] 1585
1576
[ 5. 17. 38. 62.] 1576
1362
[ 5. 17. 38. 64.] 1362
1526
[ 5. 17. 38. 66.] 1526
1056
1439
[ 5. 17. 38. 70.] 1439
1219
1266
1948
[ 5. 17. 40. 42.] 1948
1771
[ 5. 17. 40. 44.] 1771
1790
[ 5. 17. 40. 46.] 1790
2093
[ 5. 17. 40. 48.] 2093
1356
[ 5. 17. 40. 50.] 1356
2243
[ 5. 17. 40. 52.] 2243
1543
[ 5. 17. 40. 54.] 1543
2124
[ 5. 17. 40. 56.] 2124
2253
[ 5. 17. 40. 58.] 2253
2212
[ 5. 17. 40. 60.] 2212
2154
[ 5. 17. 40. 

1391
[ 5. 19. 56. 64.] 1391
1605
[ 5. 19. 56. 66.] 1605
1253
1316
[ 5. 19. 56. 74.] 1316
1771
[ 5. 19. 58. 60.] 1771
1710
[ 5. 19. 58. 62.] 1710
1480
[ 5. 19. 58. 64.] 1480
1722
[ 5. 19. 58. 66.] 1722
1352
[ 5. 19. 58. 72.] 1352
1353
[ 5. 19. 58. 74.] 1353
1674
[ 5. 19. 60. 62.] 1674
1444
[ 5. 19. 60. 64.] 1444
1723
[ 5. 19. 60. 66.] 1723
1352
[ 5. 19. 60. 72.] 1352
1317
[ 5. 19. 60. 74.] 1317
1395
[ 5. 19. 62. 64.] 1395
1628
[ 5. 19. 62. 66.] 1628
1270
1308
[ 5. 19. 62. 74.] 1308
1404
[ 5. 19. 64. 66.] 1404
1231
1026
1352
[ 5. 19. 66. 72.] 1352
1268
897
1292
[ 5. 21. 25. 27.] 1292
1851
[ 5. 21. 25. 29.] 1851
1452
[ 5. 21. 25. 31.] 1452
1796
[ 5. 21. 25. 34.] 1796
1819
[ 5. 21. 25. 36.] 1819
1236
1834
[ 5. 21. 25. 40.] 1834
1596
[ 5. 21. 25. 42.] 1596
1596
[ 5. 21. 25. 44.] 1596
1383
[ 5. 21. 25. 46.] 1383
1777
[ 5. 21. 25. 48.] 1777
1846
[ 5. 21. 25. 52.] 1846
1289
[ 5. 21. 25. 54.] 1289
1728
[ 5. 21. 25. 56.] 1728
1854
[ 5. 21. 25. 58.] 1854
1829
[ 5. 21. 25. 60.] 1829
1760
[ 5. 21. 

1301
[ 5. 23. 34. 44.] 1301
1324
[ 5. 23. 34. 46.] 1324
1548
[ 5. 23. 34. 48.] 1548
1640
[ 5. 23. 34. 52.] 1640
1538
[ 5. 23. 34. 56.] 1538
1640
[ 5. 23. 34. 58.] 1640
1595
[ 5. 23. 34. 60.] 1595
1557
[ 5. 23. 34. 62.] 1557
1621
[ 5. 23. 34. 64.] 1621
1504
[ 5. 23. 34. 66.] 1504
1504
[ 5. 23. 34. 72.] 1504
1651
[ 5. 23. 36. 40.] 1651
1600
[ 5. 23. 36. 42.] 1600
1316
[ 5. 23. 36. 44.] 1316
1333
[ 5. 23. 36. 46.] 1333
1584
[ 5. 23. 36. 48.] 1584
1652
[ 5. 23. 36. 52.] 1652
1544
[ 5. 23. 36. 56.] 1544
1652
[ 5. 23. 36. 58.] 1652
1605
[ 5. 23. 36. 60.] 1605
1568
[ 5. 23. 36. 62.] 1568
1633
[ 5. 23. 36. 64.] 1633
1513
[ 5. 23. 36. 66.] 1513
1513
[ 5. 23. 36. 72.] 1513
1635
[ 5. 23. 40. 42.] 1635
1347
[ 5. 23. 40. 44.] 1347
1363
[ 5. 23. 40. 46.] 1363
1594
[ 5. 23. 40. 48.] 1594
1686
[ 5. 23. 40. 52.] 1686
1578
[ 5. 23. 40. 56.] 1578
1686
[ 5. 23. 40. 58.] 1686
1640
[ 5. 23. 40. 60.] 1640
1603
[ 5. 23. 40. 62.] 1603
1667
[ 5. 23. 40. 64.] 1667
1548
[ 5. 23. 40. 66.] 1548
1548
[ 5. 23. 40. 72

2097
[ 5. 25. 48. 64.] 2097
2446
[ 5. 25. 48. 66.] 2446
1560
[ 5. 25. 48. 68.] 1560
1567
[ 5. 25. 48. 70.] 1567
1879
[ 5. 25. 48. 72.] 1879
1903
[ 5. 25. 48. 74.] 1903
1603
[ 5. 25. 50. 52.] 1603
1137
1526
[ 5. 25. 50. 56.] 1526
1608
[ 5. 25. 50. 58.] 1608
1590
[ 5. 25. 50. 60.] 1590
1571
[ 5. 25. 50. 62.] 1571
1344
[ 5. 25. 50. 64.] 1344
1545
[ 5. 25. 50. 66.] 1545
979
1084
1175
1217
1846
[ 5. 25. 52. 54.] 1846
2489
[ 5. 25. 52. 56.] 2489
2638
[ 5. 25. 52. 58.] 2638
2611
[ 5. 25. 52. 60.] 2611
2540
[ 5. 25. 52. 62.] 2540
2197
[ 5. 25. 52. 64.] 2197
2530
[ 5. 25. 52. 66.] 2530
1645
[ 5. 25. 52. 68.] 1645
1670
[ 5. 25. 52. 70.] 1670
1969
[ 5. 25. 52. 72.] 1969
1994
[ 5. 25. 52. 74.] 1994
1775
[ 5. 25. 54. 56.] 1775
1855
[ 5. 25. 54. 58.] 1855
1828
[ 5. 25. 54. 60.] 1828
1796
[ 5. 25. 54. 62.] 1796
1405
[ 5. 25. 54. 64.] 1405
1747
[ 5. 25. 54. 66.] 1747
1227
1187
1176
1640
[ 5. 25. 54. 74.] 1640
2492
[ 5. 25. 56. 58.] 2492
2465
[ 5. 25. 56. 60.] 2465
2421
[ 5. 25. 56. 62.] 2421
2075
[ 5.

2131
[ 5. 29. 38. 58.] 2131
2097
[ 5. 29. 38. 60.] 2097
2086
[ 5. 29. 38. 62.] 2086
1849
[ 5. 29. 38. 64.] 1849
2023
[ 5. 29. 38. 66.] 2023
1365
[ 5. 29. 38. 68.] 1365
1777
[ 5. 29. 38. 70.] 1777
1612
[ 5. 29. 38. 72.] 1612
1658
[ 5. 29. 38. 74.] 1658
2542
[ 5. 29. 40. 42.] 2542
2433
[ 5. 29. 40. 44.] 2433
2359
[ 5. 29. 40. 46.] 2359
2760
[ 5. 29. 40. 48.] 2760
1835
[ 5. 29. 40. 50.] 1835
2932
[ 5. 29. 40. 52.] 2932
2038
[ 5. 29. 40. 54.] 2038
2776
[ 5. 29. 40. 56.] 2776
2942
[ 5. 29. 40. 58.] 2942
2899
[ 5. 29. 40. 60.] 2899
2839
[ 5. 29. 40. 62.] 2839
2481
[ 5. 29. 40. 64.] 2481
2808
[ 5. 29. 40. 66.] 2808
1829
[ 5. 29. 40. 68.] 1829
1944
[ 5. 29. 40. 70.] 1944
2194
[ 5. 29. 40. 72.] 2194
2212
[ 5. 29. 40. 74.] 2212
2128
[ 5. 29. 42. 44.] 2128
2086
[ 5. 29. 42. 46.] 2086
2406
[ 5. 29. 42. 48.] 2406
1562
[ 5. 29. 42. 50.] 1562
2550
[ 5. 29. 42. 52.] 2550
1651
[ 5. 29. 42. 54.] 1651
2412
[ 5. 29. 42. 56.] 2412
2555
[ 5. 29. 42. 58.] 2555
2532
[ 5. 29. 42. 60.] 2532
2453
[ 5. 29. 42. 62

2260
[ 5. 31. 52. 62.] 2260
2077
[ 5. 31. 52. 64.] 2077
2273
[ 5. 31. 52. 66.] 2273
1373
[ 5. 31. 52. 68.] 1373
1549
[ 5. 31. 52. 70.] 1549
1877
[ 5. 31. 52. 72.] 1877
1625
[ 5. 31. 52. 74.] 1625
1396
[ 5. 31. 54. 56.] 1396
1462
[ 5. 31. 54. 58.] 1462
1445
[ 5. 31. 54. 60.] 1445
1410
[ 5. 31. 54. 62.] 1410
1173
1379
[ 5. 31. 54. 66.] 1379
894
968
972
1212
2219
[ 5. 31. 56. 58.] 2219
2202
[ 5. 31. 56. 60.] 2202
2154
[ 5. 31. 56. 62.] 2154
1958
[ 5. 31. 56. 64.] 1958
2136
[ 5. 31. 56. 66.] 2136
1364
[ 5. 31. 56. 68.] 1364
1476
[ 5. 31. 56. 70.] 1476
1753
[ 5. 31. 56. 72.] 1753
1596
[ 5. 31. 56. 74.] 1596
2350
[ 5. 31. 58. 60.] 2350
2271
[ 5. 31. 58. 62.] 2271
2078
[ 5. 31. 58. 64.] 2078
2284
[ 5. 31. 58. 66.] 2284
1376
[ 5. 31. 58. 68.] 1376
1555
[ 5. 31. 58. 70.] 1555
1877
[ 5. 31. 58. 72.] 1877
1636
[ 5. 31. 58. 74.] 1636
2254
[ 5. 31. 60. 62.] 2254
2061
[ 5. 31. 60. 64.] 2061
2284
[ 5. 31. 60. 66.] 2284
1359
[ 5. 31. 60. 68.] 1359
1539
[ 5. 31. 60. 70.] 1539
1877
[ 5. 31. 60. 72.] 187

2363
[ 5. 36. 44. 52.] 2363
1704
[ 5. 36. 44. 54.] 1704
2233
[ 5. 36. 44. 56.] 2233
2373
[ 5. 36. 44. 58.] 2373
2327
[ 5. 36. 44. 60.] 2327
2290
[ 5. 36. 44. 62.] 2290
2035
[ 5. 36. 44. 64.] 2035
2243
[ 5. 36. 44. 66.] 2243
1537
[ 5. 36. 44. 68.] 1537
1531
[ 5. 36. 44. 70.] 1531
1702
[ 5. 36. 44. 72.] 1702
1826
[ 5. 36. 44. 74.] 1826
2211
[ 5. 36. 46. 48.] 2211
1371
[ 5. 36. 46. 50.] 1371
2291
[ 5. 36. 46. 52.] 2291
1614
[ 5. 36. 46. 54.] 1614
2151
[ 5. 36. 46. 56.] 2151
2301
[ 5. 36. 46. 58.] 2301
2263
[ 5. 36. 46. 60.] 2263
2201
[ 5. 36. 46. 62.] 2201
1956
[ 5. 36. 46. 64.] 1956
2198
[ 5. 36. 46. 66.] 2198
1399
[ 5. 36. 46. 68.] 1399
1371
[ 5. 36. 46. 70.] 1371
1707
[ 5. 36. 46. 72.] 1707
1720
[ 5. 36. 46. 74.] 1720
1666
[ 5. 36. 48. 50.] 1666
2751
[ 5. 36. 48. 52.] 2751
1899
[ 5. 36. 48. 54.] 1899
2594
[ 5. 36. 48. 56.] 2594
2761
[ 5. 36. 48. 58.] 2761
2735
[ 5. 36. 48. 60.] 2735
2650
[ 5. 36. 48. 62.] 2650
2313
[ 5. 36. 48. 64.] 2313
2658
[ 5. 36. 48. 66.] 2658
1691
[ 5. 36. 48. 68

2741
[ 5. 40. 48. 60.] 2741
2663
[ 5. 40. 48. 62.] 2663
2335
[ 5. 40. 48. 64.] 2335
2664
[ 5. 40. 48. 66.] 2664
1689
[ 5. 40. 48. 68.] 1689
1775
[ 5. 40. 48. 70.] 1775
2080
[ 5. 40. 48. 72.] 2080
2046
[ 5. 40. 48. 74.] 2046
1832
[ 5. 40. 50. 52.] 1832
1290
[ 5. 40. 50. 54.] 1290
1747
[ 5. 40. 50. 56.] 1747
1837
[ 5. 40. 50. 58.] 1837
1806
[ 5. 40. 50. 60.] 1806
1795
[ 5. 40. 50. 62.] 1795
1559
[ 5. 40. 50. 64.] 1559
1754
[ 5. 40. 50. 66.] 1754
1123
1280
[ 5. 40. 50. 70.] 1280
1348
[ 5. 40. 50. 72.] 1348
1383
[ 5. 40. 50. 74.] 1383
2034
[ 5. 40. 52. 54.] 2034
2778
[ 5. 40. 52. 56.] 2778
2938
[ 5. 40. 52. 58.] 2938
2893
[ 5. 40. 52. 60.] 2893
2835
[ 5. 40. 52. 62.] 2835
2487
[ 5. 40. 52. 64.] 2487
2801
[ 5. 40. 52. 66.] 2801
1833
[ 5. 40. 52. 68.] 1833
1938
[ 5. 40. 52. 70.] 1938
2194
[ 5. 40. 52. 72.] 2194
2208
[ 5. 40. 52. 74.] 2208
1960
[ 5. 40. 54. 56.] 1960
2044
[ 5. 40. 54. 58.] 2044
1999
[ 5. 40. 54. 60.] 1999
1985
[ 5. 40. 54. 62.] 1985
1583
[ 5. 40. 54. 64.] 1583
1907
[ 5. 40. 5

2132
[ 5. 46. 48. 62.] 2132
1896
[ 5. 46. 48. 64.] 1896
2160
[ 5. 46. 48. 66.] 2160
1338
[ 5. 46. 48. 68.] 1338
1311
[ 5. 46. 48. 70.] 1311
1691
[ 5. 46. 48. 72.] 1691
1652
[ 5. 46. 48. 74.] 1652
1430
[ 5. 46. 50. 52.] 1430
1021
1355
[ 5. 46. 50. 56.] 1355
1435
[ 5. 46. 50. 58.] 1435
1409
[ 5. 46. 50. 60.] 1409
1399
[ 5. 46. 50. 62.] 1399
1235
1373
[ 5. 46. 50. 66.] 1373
857
946
1061
1077
1666
[ 5. 46. 52. 54.] 1666
2229
[ 5. 46. 52. 56.] 2229
2373
[ 5. 46. 52. 58.] 2373
2335
[ 5. 46. 52. 60.] 2335
2273
[ 5. 46. 52. 62.] 2273
2026
[ 5. 46. 52. 64.] 2026
2270
[ 5. 46. 52. 66.] 2270
1453
[ 5. 46. 52. 68.] 1453
1444
[ 5. 46. 52. 70.] 1444
1785
[ 5. 46. 52. 72.] 1785
1785
[ 5. 46. 52. 74.] 1785
1593
[ 5. 46. 54. 56.] 1593
1676
[ 5. 46. 54. 58.] 1676
1638
[ 5. 46. 54. 60.] 1638
1614
[ 5. 46. 54. 62.] 1614
1319
[ 5. 46. 54. 64.] 1319
1573
[ 5. 46. 54. 66.] 1573
1071
1026
1077
1465
[ 5. 46. 54. 74.] 1465
2233
[ 5. 46. 56. 58.] 2233
2195
[ 5. 46. 56. 60.] 2195
2157
[ 5. 46. 56. 62.] 2157
1909


1885
[ 5. 56. 64. 72.] 1885
1733
[ 5. 56. 64. 74.] 1733
1724
[ 5. 56. 66. 68.] 1724
1747
[ 5. 56. 66. 70.] 1747
2060
[ 5. 56. 66. 72.] 2060
2041
[ 5. 56. 66. 74.] 2041
1262
1375
[ 5. 56. 68. 72.] 1375
1482
[ 5. 56. 68. 74.] 1482
1386
[ 5. 56. 70. 72.] 1386
1498
[ 5. 56. 70. 74.] 1498
1437
[ 5. 56. 72. 74.] 1437
2813
[ 5. 58. 60. 62.] 2813
2441
[ 5. 58. 60. 64.] 2441
2831
[ 5. 58. 60. 66.] 2831
1805
[ 5. 58. 60. 68.] 1805
1903
[ 5. 58. 60. 70.] 1903
2204
[ 5. 58. 60. 72.] 2204
2192
[ 5. 58. 60. 74.] 2192
2393
[ 5. 58. 62. 64.] 2393
2725
[ 5. 58. 62. 66.] 2725
1804
[ 5. 58. 62. 68.] 1804
1896
[ 5. 58. 62. 70.] 1896
2114
[ 5. 58. 62. 72.] 2114
2189
[ 5. 58. 62. 74.] 2189
2368
[ 5. 58. 64. 66.] 2368
1558
[ 5. 58. 64. 68.] 1558
1680
[ 5. 58. 64. 70.] 1680
2016
[ 5. 58. 64. 72.] 2016
1757
[ 5. 58. 64. 74.] 1757
1735
[ 5. 58. 66. 68.] 1735
1825
[ 5. 58. 66. 70.] 1825
2204
[ 5. 58. 66. 72.] 2204
2100
[ 5. 58. 66. 74.] 2100
1273
1383
[ 5. 58. 68. 72.] 1383
1485
[ 5. 58. 68. 74.] 1485
1448
[ 5. 

1806
[ 7.  9. 29. 50.] 1806
2747
[ 7.  9. 29. 52.] 2747
1922
[ 7.  9. 29. 54.] 1922
2651
[ 7.  9. 29. 56.] 2651
2754
[ 7.  9. 29. 58.] 2754
2718
[ 7.  9. 29. 60.] 2718
2631
[ 7.  9. 29. 62.] 2631
2253
[ 7.  9. 29. 64.] 2253
2601
[ 7.  9. 29. 66.] 2601
1727
[ 7.  9. 29. 68.] 1727
1901
[ 7.  9. 29. 70.] 1901
1987
[ 7.  9. 29. 72.] 1987
2100
[ 7.  9. 29. 74.] 2100
2085
[ 7.  9. 31. 34.] 2085
2094
[ 7.  9. 31. 36.] 2094
1557
[ 7.  9. 31. 38.] 1557
2168
[ 7.  9. 31. 40.] 2168
1941
[ 7.  9. 31. 42.] 1941
1781
[ 7.  9. 31. 44.] 1781
1704
[ 7.  9. 31. 46.] 1704
2012
[ 7.  9. 31. 48.] 2012
1441
[ 7.  9. 31. 50.] 1441
2171
[ 7.  9. 31. 52.] 2171
1346
[ 7.  9. 31. 54.] 1346
2075
[ 7.  9. 31. 56.] 2075
2179
[ 7.  9. 31. 58.] 2179
2163
[ 7.  9. 31. 60.] 2163
2073
[ 7.  9. 31. 62.] 2073
1883
[ 7.  9. 31. 64.] 1883
2084
[ 7.  9. 31. 66.] 2084
1254
1512
[ 7.  9. 31. 70.] 1512
1691
[ 7.  9. 31. 72.] 1691
1524
[ 7.  9. 31. 74.] 1524
2547
[ 7.  9. 34. 36.] 2547
1882
[ 7.  9. 34. 38.] 1882
2624
[ 7.  9. 3

In [ ]:
print(isFreq([1,2]))


In [ ]:
k = [[ 1,  2,  3,  4], [ 5,  6,  7,  8],[ 9, 10, 11, 12]]
k = np.asarray(k)
print(np.delete(k,1,0))